### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by josh-cooley** [BruTile/BruTile#10]
I'm opening this issue to start discussions around the possibility of an asynchronous API.  It would be nice if an ITileProvider could optionally provide tiles in an asynchronous manner.    If this feature were to be implemented, would it be something to do before freezing the API in 1.0?  Would it be some new interface that could be optional and available post 1.0?

The argument for this is that a large batch of tile requests that end up timing out could fill the thread pool.  Additional requests could not be made while the thread pool threads wait.  The goal of the async api would be to leverage framework APIs that would free the thread pool to process additional requests.  If this is not possible, then the feature isn't as useful for background work.

**Comment by josh-cooley** [comment]
I may take another stab at an extension method since that would allow a lot more flexibility, but my current implementation uses the HttpTileSource as an IRequest for building new Async versions of the classes.  This allowed client side caching to be incorporated into the GetTile request.  You can see my current work in the tile-provider-async branch I have.
https://github.com/josh-cooley/BruTile/tree/tile-provider-async

**Comment by pauldendulk** [comment]
It looks like reuse through an extension method is not possible in your case because you need access to the persistent cache field. I added a PersistentCache property. This should allow an extension method as above. The GetTile should be changed to mimic WebTileProvider.GetTile.

**Comment by josh-cooley** [comment]
I'll give it a shot.  I had prototyped an async cache, but I don't believe that's necessary.

**Comment by josh-cooley** [comment]
Turns out the PersistentCache is not accessible from the HttpTileSource.  Accessing it from the WebTileProvider works if I stick with the wrapper pattern I had built, but doesn't the AsyncHttpTileSource I had written.  I put a PersistentCache property on the HttpTileSource, and found that the extension method could be written and seems to solve the problem of async http requests.

**Comment by pauldendulk** [comment]
ah, of course, PersistentCache needs to be added to HttpTileSource as well. Are these changes already added to your fork?

**Comment by josh-cooley** [comment]
No.  I just hacked around for a bit.  And unless you'd like to merge in an async project, I that code will probably go away if I can just use an extension method.

**Comment by pauldendulk** [comment]
Well actually I do prefer an extension method. It is still an important extension method though because it is a very common use case. It could be part of the BruTile repository as a separate .net 4.5 project. Or it could be in its own github project (or gist) and we point to it from the BruTile main page. What do you think?

@FObermaier and what do you think?

And how should the user work with it. A snippet in a nuget package?

**Comment by pauldendulk** [comment]
I added HttpTileSource.PersistentCache to allow it's use in an extension method and added a test to demonstrate this in Tests/BruTile.Tests/Web/HttpTileSourceTests (https://github.com/BruTile/BruTile/blob/master/Tests/BruTile.Tests/Web/HttpTileSourceTests.cs)

**Comment by josh-cooley** [comment]
Thanks.  Our team has been working on other commitments, but will be taking advantage of this feature soon.
