### ISSUE TITLE
Google Maps Static API - Shows single tile repeatedly

### ISSUE THREAD

**Issue by mnkumar8** [BruTile/BruTile#100]
Hi,

In the BruTile demo project, I have changed the google map's 'mt' url to the below url. I see only one tile (or one picture) showing on the screen and the same tile is repeated across the map. I see the same tile/picture when I scroll or zoom in/out. Please see the attached picture. Please let me know what I need to do in order to see multiple tiles.

https://maps.googleapis.com/maps/api/staticmap?center=Berkeley,CA&zoom=14&size=400x400&key=<KEY>

Thanks,
Naveen Kumar

![brutile_googlemapsstaticapi_singletile](https://user-images.githubusercontent.com/11781512/51681059-859d8c00-2009-11e9-8999-5d278b87f05f.JPG)

**Comment by pauldendulk** [comment]
I don't know how the Google Maps Static API  works. Looking in the [developer guide](https://developers.google.com/maps/documentation/maps-static/dev-guide) it seems to work with a center and a zoom. To use this with BruTile you need to use a custom tile request and calculate center and zoom from the tile index.

**Comment by mnkumar8** [comment]
Thanks for the response. I have few questions below. It would be a great help if you can guide me through it. Thanks.
1) Can you please point me to the code in BruTile project where I can find help to send custom tile request.
2) Does it mean that for every tile, we need to calculate center and zoom? If so, do I need to modify the TileInfo?
