### ISSUE TITLE
Yandex maps projection

### ISSUE THREAD

**Issue by antonad** [BruTile/BruTile#104]
Hello. I am using MapsUI in my Xamarin application and going to use google maps, yandex maps, etc)

Google is working good:
`new HttpTileSource(new GlobalSphericalMercator(), "https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}", serverNodes: new string[4] { "0", "1", "2", "3" }, tileFetcher: FetchTile);
`
But yandex map is shifted, position of objects is differ on several km.
I am using next code found in sample projects:
```
                GlobalSphericalMercator gm = new GlobalSphericalMercator();
                return new HttpTileSource(gm, "https://" + (baseLayer.URL.ToLower() == "sat" ? "sat" : "vec") + "{s}.maps.yandex.net/tiles?l=" + baseLayer.URL.ToLower() + "&x={x}&y={y}&z={z}", serverNodes: new string[3]{"01", "02", "03" });

```
I guess the problem is in projection (should be 'EPSG:3395'), can you give me an example of valud code to use yanex?

**Comment by pauldendulk** [comment]
Yes, the projection is probably the issue. Since BruTile works with tiles the projection is fixed in the data and can not be altered. Therefore it is not possible to combine a tileset in EPSG:3395 with Google maps' tileset (EPSG:3857)
