### ISSUE TITLE
Tiles in MemoryCache (get all)

### ISSUE THREAD

**Issue by lukaszpitulski** [BruTile/BruTile#106]
Hi,

I try get all cached tiles in the MemoryCache and I use for it method Find(new BruTile.TileIndex(col, row, level));

**How can I get all tiles as list/array/collection?**
Without browsing the whole MemoryCache via Find (all possible columns and rows) - With high level it will be a long time process (a lot of cols & rows).

C#, BruTile 1.0.3, Mapsui 1.4.8

**Comment by charlenni** [comment]
How should this work? The cache is an unordered list depending on tile information (zoom level, row and col). So the cache has to do the same as you: search through all entries.

**Comment by lukaszpitulski** [comment]
https://github.com/Mapsui/Mapsui/issues/704#issuecomment-537406135

if this `MemoryCache._bitmaps` wasn't private, it would be ok.

**Comment by charlenni** [comment]
But for what do you need this?

**Comment by lukaszpitulski** [comment]
To get all tiles (png) from the Mapsui(1.4.8).UI.Wpf.MapControl->Map.Viewport (.Extent)

**Comment by lukaszpitulski** [comment]
https://github.com/Mapsui/Mapsui/issues/704#issuecomment-537431363

**Comment by charlenni** [comment]
Write your own MemoryCache?

**Comment by lukaszpitulski** [comment]
Yeah right. Any simpler way? ;)

**Comment by charlenni** [comment]
Isn’t it simple enough? Derive from MemiryCache and add a property “Bitmaps”. When creating your tile source use your own cache.

Perhaps you could create a new dictionary, where you could store min and max for all rows and cold for each zoom level.

**Comment by lukaszpitulski** [comment]
Thanks.

**Comment by pauldendulk** [comment]
@lukaszpitulski Yes, as Charlenni says. You could start out by copying the MemoryCache in BruTile and modify it to your own needs.
