### ISSUE TITLE
Format of TileIndex

### ISSUE THREAD

**Issue by charlenni** [BruTile/BruTile#109]
I encountered a problem with TileIndex. If you work with TMS, and at the same time, OSM providers, you don't know, if the TileIndex is in TMS or OSM format. And if you know, there isn't something to convert between them. Or didn't I see it?

**Comment by pauldendulk** [comment]
You can get the format on a tilessource with:
```csharp
var schemaType = TileSource.Schema.YAxis; // returns TMS or OSM
```
But why do you need it? There are few scenarios where you need to know? Perhaps there is another approach to your problem.

**Comment by charlenni** [comment]
I'm creating vector tiles with Mapbox GL style files. This style files could contain not only one source, but more. So you could have a hilshading raster map in the background that with higher zoom levels vanishs. This hilshade tile source could use OSM, while the vector tile source uses TMS. To get now the correct raster and vector tiles to draw at the same time, you have to convert the tile info regarding the tile source that is used. I hope, I could describe it correct.

**Comment by pauldendulk** [comment]
You cannot put them in separate tilesources with different schaschema's? Draw one layer semi transparent over the other?

**Comment by charlenni** [comment]
Yes, sure, I could do this. No problem. But it would be nice to know, what format the TileIndex has. It is a TileIndex in OSM or in TMS? The user has to know, which format the TileIndex has and how to convert it in the other format. So you have always to think about it.

**Comment by pauldendulk** [comment]
But why do you need to know if you can draw both layers correctly over each other.

**Comment by charlenni** [comment]
If I want to get a TMS tile and a OSM tile from different sources, I get different tiles. That looks very funny. So I have to think, which format the TileIndex has, and if it isn't the same than the TileSource, than I have to create a new TileInfo with the converted coordinates and use this for the access of the tile source.

**Comment by charlenni** [comment]
As example

![image](https://user-images.githubusercontent.com/4381223/75564556-a2966100-5a4c-11ea-9ee1-94e701cc0a04.png)

This is a OSM tile in the background and a vector map drawn above. I'm really save, that Madagaskar isn't part of Russia ;-) So hier the problem is, that the Y-axis is different, but the same TileInfo is used to get the tiles.

**Comment by pauldendulk** [comment]
I wrote this library am i very well aware what the yaxis problem is.

The solution is to put them in separate layers. Each with their own schema.

Now there might be a reason you can not do this but then you have to explain to my why this is the case.

**Comment by charlenni** [comment]
I have two different tile sources. one is

    https://a.tile.openstreetmap.org/{z}/{x}/{y}.png

The second is

    mbtiles://monaco.mbtiles

The first has OSM, the second one has TMS. Now I want to draw 

    Index = new TileIndex(2, 2, "2")

Both sources have a tile with the given index, but not the same tile. With doing nothing, I get the above tile.

Ok, you could say: it is your problem to know, which tile you want. But it would be helpfull to have a flag to remember, what type of TileInfo this is and some function, which could convert one format into the others.

**Comment by pauldendulk** [comment]
I understand what you want but I don't understand why you need to solve it like this. I would say you can overlay two such tile layers over each other, but let's not go further into that. I assume you have your reasons.

At the tile schema level there is the YAxis field to indicate if it is  osm or tms.  A very long time ago I we did do a calculation from one to the other. It was something like this. 
- Find out which level you are
- Find out how many tiles are in this level in the y direction. You can get this from the schema.
- Invert with: yInverted = totalTiles - y

**Comment by charlenni** [comment]
Ok, it was my problem. It isn't possible to use two different TileSources in a TileLayer. If you do this, you get this problems. So I have to create two different TileLayers, one for each TileSource, which than could have different Y axises.
