### ISSUE TITLE
Unable to configure WMS tile source with empty VendorSpecificCapabilities tag

### ISSUE THREAD

**Issue by lehmannk** [BruTile/BruTile#112]
I am trying to configure a WMS provider like such
```
string url = "http://osm.franken.de/cgi-bin/mapserv.fcgi?LAYERS=contour,contour2&NUMZOOMLEVELS=22&TYPE=png&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=getcapabilities";
WmscTileSource.CreateFromWmscCapabilties(new Uri(url)).GetEnumerator().Current;
```
the return value is always null because the provider returns an empty  `<VendorSpecificCapabilities >` tag and then `WmscTileSource.ParseVendorSpecificCapabilitiesNode` does not detect anything. In the unit tests I found the resource `BruTile/Tests/BruTile.Tests/Resources/Wms/NrcsSoilWmsCapabilities_1_1_1.xml` which also contains an empty  `<VendorSpecificCapabilities >` tag so I believe there must be a way to configure this provider

**Comment by pauldendulk** [comment]
Perhaps you can paste the content of your capabilities and paste that in NrcsSoilWmsCapabilities_1_1_1.xml and see in the debugger where the difference is.

**Comment by lehmannk** [comment]
Well, for NrcsSoilWmsCapabilities_1_1_1.xml `WmscTileSource.CreateFromWmscCapabilties` also returns null, unfortunately. So currently whenever there are no `<VendorSpecificCapabilities>` contents supplied these sources cannot be used?

**Comment by pauldendulk** [comment]
oh, I think I understand your problem. 

The ```<VendorSpecificCapabilities>``` node has been used by the TMS protocol to add tile schema information. An ordinary WMS does not have this tile schema information. You can still use it if you add the schema yourself in code. You at the 'wms called tiled' sample under 'data' in Mapsui . 

Depending on the projection you want to use it can be hard to find the right schema.

**Comment by FObermaier** [comment]
That service does not seem to work properly. Trying it with QGIS 3.10 does not return any images.

**Comment by lehmannk** [comment]
I got it working using @pauldendulk 's hint with the wms tile sample. Luckily the schema is a `GlobalSphericalMercator` so not too much fiddling was necessary. Thank you so much for your help. Awesome work !!!
