### ISSUE TITLE
Style tag in ResourceURL is incorrectly defined with capital 'S'

### ISSUE THREAD

**Issue by Hylke-Atmos** [BruTile/BruTile#114]
Hi,

We are running into some issues because (most) of our wmts service providers have a {style} tag definition with a small 's'. This also seems to be the standard from what I read [here](https://www.geowebcache.org/docs/current/services/wmts.html#feature-info-resources). 

However apparently it is not consistently used everywhere, which is probably why the BruTile Library does only accept a {Style} tag with capital. This is now resulting invalid URL's which do not provide any tiles at all.

A simple solution would be to use a regex.replace with ignoreCase mode on the tag replace functions, such as CreateResourceUrlsFromResourceUrlNode in WmtsParser.
`template = Regex.Replace(template, WmtsRequest.StyleTag, style, RegexOptions.IgnoreCase);`
Or simply add a additional replace with the style.tag toLowerCase.
`template = template.Replace(WmtsRequest.StyleTag.ToLower(), style);`

I'll also make a pull request to solve this using a regex replace.

**Comment by pauldendulk** [comment]
Will be fixed in 2.1.3. Not sure when it will be released.

**Comment by pauldendulk** [comment]
BruTile 2.1.3 was just pushed.
https://www.nuget.org/packages/BruTile/

Other changes will be part of a v3.
