### ISSUE TITLE
Use existing mbtiles file as persistent cache

### ISSUE THREAD

**Issue by spaddlewit** [BruTile/BruTile#122]
This is more of a how-to question than a bug..

I have an existing mbtiles sqlite database with tiles in it. Any tiles downloaded with BruTile, I'd like to have written to this file as a persistent cache. Is there a way to do this with the PersistentCache option? I'm having difficulty finding examples utilizing it.

**Comment by spaddlewit** [comment]
Nevermind -- the IPersistentCache interface is pretty straightfoward to implement. It still would be nice to have a Sample for this, though.

**Comment by pauldendulk** [comment]
Yes, I also though about it when working on BruTile again this week. Perhaps not distinguish between cache and data source. Just one interface for Http, MbTiles and MemoryCache. Only Http would have no Add method.

**Comment by m1dst** [comment]
I would really appreciate an example of how to do this.

**Comment by spaddlewit** [comment]
> I would really appreciate an example of how to do this.

I put this together for you. Happy to talk about it if you have questions.
https://github.com/spaddlewit/MBTilesPersistentCache

**Comment by m1dst** [comment]
@spaddlewit Thanks - I'll take a look.
