### ISSUE TITLE
Add symbol package (.snupkg) creation and publishing

### ISSUE THREAD

**Issue by donid** [BruTile/BruTile#123]
I would like to be able to step into BruTile code while debugging my application, which requires .pdb files to be available. Can you enable symbol package (.snupkg) creation and publishing for all BruTile nuget packages - see [here](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)

**Comment by pauldendulk** [comment]
There is also github source linking. I never used it myself. If that is more low maintenance I would prefer that. Do you know anything about that and how it relates to what you are suggesting?

**Comment by FObermaier** [comment]
Here is how it's done in NTS:

https://github.com/NetTopologySuite/NetTopologySuite/blob/1c463b032c116904bf76e1e07aa9017933e0d6bf/src/Directory.Build.props#L102-L112

No big deal.

**Comment by donid** [comment]
I guess you are referring to [this](https://github.com/dotnet/sourcelink). I haven't used it yet, but AFAIK it automates the second step of having the source code to debug (also known as 'source indexing').
The first step is to have symbol files (.pdb) on the nuget symbol server and the second step is that those files contain a link to to Github where the exact source file of the current debug location can be found. If you skip the second step, the pdb will contain the file-paths that you had locally during your build and when I use them on my machine, the debugger will probably fail to locate the file and show a 'File Select' dialog. Please note: 'first' and 'second' are not meant in a timing-sense, because you (obviously) have to sourcelink a pdb before you upload it to the nuget servers.
BTW: the SourceLink page shows the same XML-fragment as the Url that I posted earlier:
`    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>`
But that's all theory, because I haven't yet published any nuget packages myself...

PS: It seems typing my lengthy explanation took too long, but maybe its still useful :-)

**Comment by pauldendulk** [comment]
Thanks @FObermaier  and @donid. I added the nts configuration to BruTile and it is building snupkg's now. From [this](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package) I conclude that I do not need to explicitly push the snupkg's. So assume this is fixed. It can only be tested after the next release.

**Comment by pauldendulk** [comment]
I just published 3.1.2 and got a notification that the .snuget was published. I wondered what happened and then found this issue that I had all forgotten about. Thanks for helping @donid and @FObermaier.
