### ISSUE TITLE
build warnings and dead code

### ISSUE THREAD

**Issue by donid** [BruTile/BruTile#124]
While rebuilding BruTile (to create pdb files), I received 13 compiler warnings.
`warning CS0472: The result of the expression is always true` seems to be dead code from the conversion of 'level' from string to int.
And the others are about deprecated build-task elements.

**Comment by pauldendulk** [comment]
Thanks for pressing for quality instead of just asking for features. I just had a look. None seem really problematic. It will be fixed.

**Comment by pauldendulk** [comment]
A PR is also welcome.

**Comment by donid** [comment]
I could create a PR, but you have to be a bit forgiving - I am quite unexperienced.
