### ISSUE TITLE
Folder with map tiles as tile source

### ISSUE THREAD

**Issue by anushabasavaraj92** [BruTile/BruTile#128]
Is there a way to  make a local folder containing the map tiles in the z/x/y.png order to make a tile source? like how there is a provision for HttpTileSource?

**Comment by pauldendulk** [comment]
In BruTile desktop there is a FileTileProvider, perhaps you could take a look at that.
https://github.com/BruTile/BruTile/blob/master/BruTile.Desktop/FileSystem/FileTileProvider.cs

**Comment by anushabasavaraj92** [comment]
Do you have a sample using the instance of the class?

**Comment by im28** [comment]
Have a look here

https://github.com/BruTile/BruTile/blob/master/Tests/BruTile.Desktop.Tests/FileSystem/FileTileProviderTests.cs

**Comment by ms1094392787** [comment]
I also need an example because I want to do the same, set the tile source to a local folder. The example url given above is no longer open.
