### ISSUE TITLE
How to pan map control to specific GPS coordinates?

### ISSUE THREAD

**Issue by ju2pom** [BruTile/BruTile#131]
Congratulation for the great library!

I have the feeling that this question is pretty naïve but I don't see anything related to GPS in the code.
I found that the viewport in the demo has a center, but it's expressed in world coordinates, I have no idea how to convert GPS latitude and longitude in world coordinates. Currently I'm using tiles from the GoogleMap sample source.

Any help would be much appreciated.

Thanks.

**Comment by pauldendulk** [comment]
This is not an issue that BruTile solves. The tiles are fetched in some kind of coordinate system. This could be any coordinate system. There are specific projection libraries for this. 

In your case you need the projection from GPS [EPSG:4326](https://epsg.io/4326), to SphericalMercator [EPSG:3857](https://epsg.io/3857). This is the most common projection and Mapsui has a piece of code for that which you could copy and paste. It is here:

https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Projection/SphericalMercator.cs

Also relevant:
https://mapsui.com/documentation/projections.html
