### ISSUE TITLE
How to get bounding box without convert to Mercator

### ISSUE THREAD

**Issue by cuongnc5** [BruTile/BruTile#133]
How to I get bbox with WGS84
ex: my bbox in the mbtiles file : 108.1504,15.9458,108.3276,16.155. I want to ggot it without mercator converter?

**Comment by pauldendulk** [comment]
BruTile has no support for projections. For conversions between WGS84 (EPSG:4328) and SphericalMercator (EPSG:3857) you could copy Mapsui's class for this https://github.com/Mapsui/Mapsui/blob/master/Mapsui/Projection/SphericalMercator.cs
