### ISSUE TITLE
please add support to baidu map

### ISSUE THREAD

**Issue by yanzixiang** [BruTile/BruTile#135]
please add support to baidu map

**Comment by pauldendulk** [comment]
Perhaps you could add this through a pull request. [Here](https://github.com/BruTile/BruTile/pull/129/files) is a one adding two layers to the KnownTileSources.

Things to take into account:
- What is the licensing? It is legal to just use it? Should some subscription key be provided? If so it should be possible to add such a key.
- What is they protocol? Not every tile layer is very simple. The new google maps layers have a complicated protocol. We left it out for that reason.

**Comment by pauldendulk** [comment]
The schema might be complicated
https://github.com/BruTile/BruTile/issues/135

> Baidu Map uses a variant of web Mercator projection for slicing map data into tiles, with distances expressed in degrees. It's associated with an underlying latitude-longitude reference. However, the reference uses the BD-09 coordinate system, which adds further obfuscation to the already obfuscated national standard in China, GCJ-02[10] (which in turn is defined in terms of the de facto standard around the world, WGS 84). Baidu alleges that adopting BD-09 "protects users' privacy".[11]

**Comment by pauldendulk** [comment]
Closing this. PRs are still welcome.
