### ISSUE TITLE
KnownTileSources: http URLs do not work on iOS

### ISSUE THREAD

**Issue by janusw** [BruTile/BruTile#141]
Carry-over from Mapsui/Mapsui#1094 ...

The Bing maps from BruTile's KnownTileSources do not work on iOS, since they use http URLs:

```
Mapsui.Samples.Forms.iOS[2938:1486955]
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.
Temporary exceptions can be configured via your app's Info.plist file.
```

Switching from http to https seems to fix the problem for Bing. Other sources like OpenCycleMap and Stamen are probably also affected.

**Comment by janusw** [comment]
> Switching from http to https seems to fix the problem for Bing. Other sources like OpenCycleMap and Stamen are probably also affected.

In contrast to Bing, simply changing http to https does not seem to work for OpenCycleMap and Stamen.

**Comment by pauldendulk** [comment]
Thanks, fixed by merging your PR.
