### ISSUE TITLE
CI build failures

### ISSUE THREAD

**Issue by janusw** [BruTile/BruTile#143]
The latest CI builds all failed with multiple errors like this:

```
/home/runner/.dotnet/sdk/2.2.108/Microsoft.Common.CurrentVersion.targets(1179,5):
error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found.
To resolve this, install the SDK or Targeting Pack for this framework version or
retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.
Note that assemblies will be resolved from the Global Assembly Cache (GAC)
and will be used in place of reference assemblies.
Therefore your assembly may not be correctly targeted for the framework you intend.
[/home/runner/work/BruTile/BruTile/BruTile/BruTile.csproj]
```

Also the following warning occurs:
```
Warning: /home/runner/.dotnet/sdk/2.2.108/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(153,5):
warning NETSDK1071: A PackageReference to 'Microsoft.NETCore.App' specified a Version of `2.1.0`.
Specifying the version of this package is not recommended.
For more information, see https://aka.ms/sdkimplicitrefs
[/home/runner/work/BruTile/BruTile/Tools/GetVersionFromAssembly/GetVersionFromAssembly.csproj]
```

**Comment by pauldendulk** [comment]
Made some changes, see https://github.com/BruTile/BruTile/pull/146. Still a lot of projects use net48. Also the specific package version was removed to fix the warning.

**Comment by pauldendulk** [comment]
I added a BruTile-Build.sln. Added code, tests, and tools and use that for building. Now the build succeeds for github actions.

The samples have to be added at some point too. After that BruTile.sln should be deleted and BruTile-Build.sln should be renamed to BruTile.sln.

btw. There still is an appveyor build for BruTile.sln that succeeds.

**Comment by pauldendulk** [comment]
For your information. Some things done today:

- All csproj'es to the new format
- All libraries to .netstandard2.0.
- All tests, samples and tools .netcoreapp3.1
- Deleted BruTile.Desktop and BruTile.Desktop.Cache and move the two files in them to BruTile.

There are no .NET Framework projects in the repository anymore. ✌️

Yet there is one WPF project and two Windows.Forms projects, which wont run on Mac (as far as I know). 

We should think about an alternative. All code should build on Windows and Mac. I looked at MAUI, but it seems early. Contributors will have to install specific prereleases. Perhaps just wait a bit longer.

**Comment by pauldendulk** [comment]
Building the github action on Windows now, so there is no real need to convert anything, al least not for my since I do not run it on Mac. If there sample projects need to be cross platform I think the best option is Avalonia. The we can run on Mac and let github actions use linux, which is much faster.
