### ISSUE TITLE
Online base tiles disappears on zoom past certain level

### ISSUE THREAD

**Issue by Scott2142** [BruTile/BruTile#145]
Expected behaviour

Tile layer does not disappear on zoom in.
Actual behaviour

Tile layer disappears after zooming past a point. It seems to be when the zoom level exceeds the specified max zoom.

Screenshots
![image](https://user-images.githubusercontent.com/70848935/112238818-7bcf4c00-8c99-11eb-8e8e-99dab9a7481d.png)
![image](https://user-images.githubusercontent.com/70848935/112238825-7ffb6980-8c99-11eb-9326-2870daa46d37.png)

**Comment by pauldendulk** [comment]
It looks like this problem is related to how BruTile is used. Where are you calling this from?

One possible cause could be how the renderer deals with zoom levels below the level of available tiles. 

Another could be in the definition of the tile schema. The tile schema of the aerial layer might have an extra zoom level defined beyond what is available. In that case it will try to fetch tiles that do not exist and show nothing instead.

**Comment by Scott2142** [comment]
We're calling BruTile via DotSpatial. 

The code we are using is below. We are specifying the min and max zoom levels, but they don't seem to be doing anything. There is a difference between two tile source URLs were are using of 19 and 20 for the max Zoom, but the tiles disappear at the same zoom level for both.

It would be great if the tiles remained visible but just became pixelated as the zoom level went beyond the specified max zoom.

```
private void LoadBrutileURL(string url, string name, int minZoom, int maxZoom)
        {
            var fileCache = (Func<ITileCache<byte[]>>)(() => new FileCache(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "TileCache", name), string.Empty, new TimeSpan(30, 0, 0, 0)));

            // Setup the HTTP Tile Source
            var urlFormatter = url;
            var tileSource = new HttpTileSource(new GlobalSphericalMercator(minZoom, maxZoom), urlFormatter, new[] { "0", "1", "2", "3" });

            // Load the Tile into the Provider
            var tileServiceProvider = new BrutileServiceProvider(name, tileSource, fileCache());

            // Add and Load the Provider via the DropDown (not visible, programmatic)
            ClearTileProviders();

            _tileProviderDropDown.Items.Add(tileServiceProvider);
            _tileProviderDropDown.SelectedItem = tileServiceProvider;
        }
```

**Comment by pauldendulk** [comment]
I assume this code is for the aerial layer not the overlay.

If the minZoom and maxZoom are within the range of available tiles then that part should be okay. It could also be the way DotSpatial calls the layer that matters. It could also be the fileCache causing trouble. What happens if you remove the fileCache?

**Comment by Scott2142** [comment]
Correct, this code is just for the areial view. 

I tried setting the minZoom and maxZoom levels to be within the avaliable range. This had the effect of stopping layers being shown at the higher zoom levels excluded. But instead of disappearing the failed to load image was shown (see screenshot). Could this mean that dotspatial is overriding the maxZoom level in some way?

I also tried setting the fileCache to null. This didn't seem to change the behaviour. 

![image](https://user-images.githubusercontent.com/70848935/112704666-85ea8800-8eef-11eb-943f-22eff9267437.png)

**Comment by pauldendulk** [comment]
Every layer has it's own tile schema and own zoom limits. In this case there are two layers with different limits. This does not have to be a problem. How to go about this is up to the library that is using BruTile. 

The zoom limits of the available tiles do not have to be identical to the zoom limits of the layer. In Mapsui the MinVisible and MaxVisible determine if a layer is shown at all. These may be different limits than the limits of the available tiles. If DotSpatial does not have this distinction this will be hard to fix. 

If it does have this distinction there is the case where the zoom is within the layer limits and outside the available tiles limits. In this situation the library has to make some choice.  In Mapsui we look for the nearest available zoom level and fetch those tiles. Perhaps this is not built into DotSpatial.

Another thing to take into account is the zoom limits of the entire map. So, those are three different things:
- Limits of the available tiles within a tile layer
- Limits of the layers
- Limits of the map

It seems a DotSpatial developer should look into what is happening here.

**Comment by Scott2142** [comment]
Thanks Paul. I'll try to investigate within DotSpatial. 
Much appreaciated.

**Comment by Scott2142** [comment]
I have found the cause of the issue. This was definetely a DotSpatial issue. The current code hard codes the allowed Zoom levels to a maximum of 18. When the zoom level exceeds this is was set as -1 which makes the tile disappear. 

I have reported this on the DotSpatial page and a fix has been proposed (still to be approved)

https://github.com/DotSpatial/DotSpatial/issues/1390

**Comment by pauldendulk** [comment]
ah, thanks for the feedback.
