### ISSUE TITLE
Support for Time Dimension of WMTS

### ISSUE THREAD

**Issue by BananaFritters** [BruTile/BruTile#156]
Some WMTS-Server have a time dimension usually with {Time} placeholder. These are currently not supported by BruTile. Could this be implemented?

Example of Layers with time dimension:

[https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml](https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml)

**Comment by pauldendulk** [comment]
This is not something I will find time for.

**Comment by pauldendulk** [comment]
But it is something that would fit in BruTile.
