### ISSUE TITLE
GeoJson Support?

### ISSUE THREAD

**Issue by alirezanet** [BruTile/BruTile#159]
Hello,
does this library support GEO-JSON data? I have a MongoDB database with a lot of GeoJSON data. I want to show these data on my client app that using leaflet. (leaflet supports TMS and WMS ...)

Is possible to use BruTile to somehow serve my data to the client? 
I appreciate any guidance

**Comment by KevinBTech** [comment]
Hello,

This issue also concerned me. Have you find something ?

**Comment by pauldendulk** [comment]
I think BruTile should not support vector data explicitly (adding Point, Line, Polygon classes), this would add too much extra logic, but perhaps it is possible to treat the GEO-JSON just as a binary stream, so, we would fetch it from the database and return it 'as is'. Is the data you have on the server side stored as tiles? Or could the database itself select tiles out of the geometry data? I can image BruTile doing a request for a geojson tile with the extent that is needed and just returning the data. 

Some thing to take into account is that if there i a lot of data you usually want to have some simplification of data on the zoomed-out levels. This is not something that BruTile could do without vector data support.

**Comment by KevinBTech** [comment]
I would like to host my own OSM server which is based on a docker image (cf [https://github.com/Overv/openstreetmap-tile-server](https://github.com/Overv/openstreetmap-tile-server)).

I also need to generates tiles from KML or GeoJson files. Those are heavy (100 MB to 2 GB).
That's why I can not load them from Leaflet plugin.

Am I in the good direction or am I wrong ?

**Comment by pauldendulk** [comment]
BruTile is not a good option if you need vector support (KML or GeoJSON). This is also something that is not on the roadmap. BruTile could only be interesting if it can treat the files as streams and leave the parsing to the consuming library. If something is blocking this scenario a specific issue could be submitted.
