### ISSUE TITLE
MbTiles flashes at low zoom level

### ISSUE THREAD

**Issue by gpsaliola** [BruTile/BruTile#160]
When add a mbtile layer to mapsui map and show the map at zoom level < 16, the tiles flashes.
If the zoom level is higher the drawing is stable.  
I'm testing on iOS phisical device.

**Comment by pauldendulk** [comment]
Are you sure zoom level < 16 is available in your MbTiles?

**Comment by gpsaliola** [comment]
In tiles table the zoom_level field is set to 17.
I would understand if below level 17 you do not see the tiles but not that they flash.

**Comment by pauldendulk** [comment]
I am closing this because I've let this get old. If this still is an easy it is better to submit it as an issue to Mapsui. It might be possible to solve this by setting the min/max resolutions or the MinVisible/MaxVisible.
