### ISSUE TITLE
BruTile.sln cannot be built with VS for Mac

### ISSUE THREAD

**Issue by janusw** [BruTile/BruTile#163]
... because restoring packages fails like this:

```
Getting restore information for solution /Users/janus/github/BruTile/BruTile.sln
/usr/local/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/Users/janus/github/BruTile/Samples/BruTile.Samples.SimpleStaticMap/BruTile.Samples.SimpleStaticMap.csproj]
/usr/local/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/Users/janus/github/BruTile/Samples/BruTile.Samples.MbTiles/BruTile.Samples.MbTiles.csproj]
/usr/local/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/Users/janus/github/BruTile/Samples/BruTile.Demo/BruTile.Demo.csproj]
MSBuild exited with code 1
```

The first two seem to be Windows.Forms projects, and the last one WPF.

There are at least two ways around this problem:
1) Convert those samples to a cross-platform framework (like Xamarin.Forms or MAUI).
2) Add a Mac-specific sln that excludes the Windows stuff (as for Mapsui).

**Comment by janusw** [comment]
>     2. Add a Mac-specific sln that excludes the Windows stuff (as for Mapsui).

Just saw that there is a BruTile-Build.sln, which might be just what I need for Mac. Apparently it was introduced for doing a GitHub Actions CI build (on an Ubuntu host).

**Comment by pauldendulk** [comment]
> Convert those samples to a cross-platform framework (like Xamarin.Forms or MAUI).

What about Avalonia? If we use that for the samples I assume it can be used for Windows, Mac and Ubuntu.

**Comment by janusw** [comment]
> > Convert those samples to a cross-platform framework (like Xamarin.Forms or MAUI).
> 
> What about Avalonia? If we use that for the samples I assume it can be used for Windows, Mac and Ubuntu.

Yeah, Avalonia might also be an option. I don't have any experience with it, though.

**Comment by pauldendulk** [comment]
> Yeah, Avalonia might also be an option. I don't have any experience with it, though.

There is sample now in Mapsui master that I use regularly for testing. I had to fix for some small things which was possible without any deep knowledge. Mostly it is similar to WPF. I can not judge how stable it is. I encountered one thing that seemed to function incorrectly.

**Comment by pauldendulk** [comment]
I added a BruTile.slnf to build on Mac and Linux. It only contains a very simple console sample. The other samples could be converted to Avalonia, or in this case Eto.Forms might be an easy option to migrate them. The EpsgAccessDatabase project is another kind of project. I don't have a solution for that in mind.
