### ISSUE TITLE
WmtsTileSchema name of TileMatrixSet and Layer

### ISSUE THREAD

**Issue by josh-cooley** [BruTile/BruTile#18]
The comments in WmtsTileSchema indicate that the Identifier property should contain the identifier for the TileMatrixSet, but WmtsParser sets that to the identifier for the layer.  In WmtsTileSchema.CreateSpecific, the Name property is set first to identifier (which contains the identifier for the layer) then is set to the name of *this* which contains the TileMatrixSet.

I need the value of both the layer and the TileMatrixSet, but I don't believe the values are stored in the right location based on the comments.  Also CreateSpecific sets Name twice, which appears to be an error.  What should be stored in these two properties?

**Comment by FObermaier** [comment]
As there is no "WmtsTileSource" which could hold properties for `Layer.Title` and `Layer.Identifier` these are put in WmtsTileSchema when calling `WmtsTileSchema.CreateSpecific`.
This is of course a "dirty" hack. Why do you need the "original" name of the TileMatrixSet. Isn't SRS or CrsIdentifier sufficient?

You are right that there is a bug in CreateSpecific on setting `Name` twice.

**Comment by josh-cooley** [comment]
I'm looking to present some configuration information to the user.  Perhaps I should be working with the capabilities document directly, but the library already extracts the pieces I need.  I need the TileMatrixSet because this is the configuration input for another system that is not using BruTile.  I know what we are doing is putting a hack on top of a hack, so the answer may be to do this differently.

Should the TileMatrixSet be stored in the WmtsTileSchema.Identifier property, or does the comment on the Identifier property need to be corrected?

**Comment by FObermaier** [comment]
As WmtsTileSchema is neither WMTS Layer nor WMTS Tilematrixset but a mix of both, we should name the properties of both.
```C#
public string Identifier { get { return Layer + "(" + TileMatrixSet + ")"; }
public string Layer[Identifier] { get; set;}
public string [Layer]Title { get; set; }
public string TileMatrixSet[Identifier]{ get; set; }
```
The code documentation has to be fixed, that is for sure.

**Comment by josh-cooley** [comment]
I've attempted to follow your advice with the following pull request.  Please provide feedback on how that's implemented.
https://github.com/BruTile/BruTile/pull/19

**Comment by josh-cooley** [comment]
Closing since the submitted pull request has been merged.
