### ISSUE TITLE
MemoryCache causing excessive blocking garbage collections and a possible fix for the issue.

### ISSUE THREAD

**Issue by JPhilC** [BruTile/BruTile#180]
First of all, thank you for providing this repository and code.

I recently noticed performance issues in an application I am working on that uses the BruTile code. Using Performance Profiler in Visual Studio I noticed that the problem was due to a mass of blocking garbage collections shortly before the UI was rendered. The caused the application to be unresponsive for a few seconds.

I narrowed it down to the MemoryCache class and specifically calls to the GetNextCacheVersion method in the Find method. 

To fix the issue I replaced all calls to GetNextCacheVersion() in the class with DateTime.Now.Ticks. It seems to work well.

Kind regards,

Phil

**Comment by pauldendulk** [comment]
Thanks for the report. It is important to avoid such blocking garbage collections. It is hard to understand why GetNextCacheVersion would affect this. It does nothing related to garbage collection, nothing is created, it only increments a long, this is one of the simplest operations I can think of. Perhaps the change alters the way the cache is cleaned somehow, yet, we do need to clean the cache at some point. So I would have to further investigate what is going on before I make any changes.

Would it be possible for me to reproduce this problem? What kind of setup was it?

**Comment by pauldendulk** [comment]
There could be a performance problem related to the MemoryCache, but I have to little information to investigate it. This is the implementation of GetNextCacheVersion.

```csharp
        public long GetNextCacheVersion()
        {
            _cacheVersion++;
            return _cacheVersion;
        }
```

btw, it is also possible to create your own implementation of the IMemoryCache.
