### ISSUE TITLE
Add "Referer" property to HttpTileSource

### ISSUE THREAD

**Issue by gpsaliola** [BruTile/BruTile#213]
I've seen that HttpTileSource has the property "userAgent" to specify the relative http header.
It would be great if there was also the "Referer" property.
In this way developers are not forced to implement tileFetcher to add this http header.
Some maps require this http header () such as Mapy maps [https://mapserver.mapy.cz/turist-m/{z}-{x}-{y}](https://mapserver.mapy.cz/turist-m/%7Bz%7D-%7Bx%7D-%7By%7D) (Referer: "https://en.mapy.cz/").
The tileFetcher implementation often crashes the app as described in https://github.com/Mapsui/Mapsui/issues/2114.
Thanks.

**Comment by pauldendulk** [comment]
Discussed in a Mapsui issue https://github.com/Mapsui/Mapsui/discussions/2117#discussioncomment-7020914

**Comment by pauldendulk** [comment]
Merged PR. Assuming this is fixed in the next release.

**Comment by pauldendulk** [comment]
The referer parameter was added in 5.0.5 and removed again in 5.0.6 because it turned out to be breaking change for compiled code https://github.com/BruTile/BruTile/pull/221
