### ISSUE TITLE
WmscRequest Configurable Connection Timeout

### ISSUE THREAD

**Issue by nm4568** [BruTile/BruTile#228]
Is there a way to specify a custom timeout when using the WmscRequest class with HttpTileProvider?

**Comment by pauldendulk** [comment]
In BruTile 6 you will have to use the HttpTileSource instead (HttpTileProvider was removed). The GetTileAsync will have the HttpClient as parameter so you can control this on the outside.

**Comment by pauldendulk** [comment]
@nm4568 At the moment I don't know any wmsc service. If you have any for me I would like to add it to the tests (local copy of the capabilities) and to the samples.

**Comment by nm4568** [comment]
@pauldendulk sure thing, here is the service I'm using which is the NOAA Electronic Navigation Charts (ENC).

https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService/WMSServer?request=GetCapabilities&service=WMS

**Comment by pauldendulk** [comment]
Scrolling through the capabilities this looks like an ordinary WMS to me. So you use the WmscRequest (renamed to WmscUrlBuilder in v6) and there is no parsing of a WMSC capabilities. I think this is a thing of the past and we should not invest in this. We still have a unit test that parses a wmsc capabilities. We should keep that as long as it does not cause problems. Tiled request of a regular WMS using the WmscUrlBuilder will remain in use.
