### ISSUE TITLE
WmtsParser fails to parse response -  LowerBound and UpperBound are lacking the ows prefix

### ISSUE THREAD

**Issue by FObermaier** [BruTile/BruTile#25]
A null-reference exception occurs on line 129 in ucWmtsLayerConfiguration.cs when connectiong to this url:

http://maps-open.lantmateriet.se/open/topowebb-ccby/v1/wmts?request=GetCapabilities&version=1.0.0&service=wmts

**Comment by pauldendulk** [comment]
Thanks a lot for the clear report.

**Comment by pauldendulk** [comment]
Some xml elements are missing the 'ows' namespace which is basically a flow in the xml. To make it work the XmlSerializer.Deserialize should include the empty namespace as well. Late last night I did not find a solution for this.

**Comment by pauldendulk** [comment]
@pedwik So, lets talk about this over here.

**Comment by FObermaier** [comment]
Looking at the other GetCapabilities responses handled by the testsuite on could argue that the one in question is _not valid_.
How do other open-source programs deal with it (e.g. QuantumGis)?
Maybe WmtsParser should exit more gracefully.

**Comment by pedwik** [comment]
Just FYI, it works fine in QGis. In TatukGis there is some problem, the background image is placed completely outside the target.

**Comment by pauldendulk** [comment]
WmtsParser should definitely not crash on it. Also I think BruTile should just parse this as intended. An option for the desparate is to use a TextReader and strip all the namespaces from the xml.

**Comment by FObermaier** [comment]
Here is a possible fix for this.
[0001-Attempt-to-fix-Xml-De-Serialization-of-malformed-Bou.patch.txt](https://github.com/BruTile/BruTile/files/32668/0001-Attempt-to-fix-Xml-De-Serialization-of-malformed-Bou.patch.txt)

**Comment by pedwik** [comment]
I noticed that in the wmts xml file (http://maps-open.lantmateriet.se/open/topowebb-ccby/v1/wmts?request=GetCapabilities&version=1.0.0&service=wmts), there is a bounding box tag for each TileMatrixSet, for example: 

<ows:BoundingBox crs="urn:ogc:def:crs:EPSG:6.3:3857">
        <LowerCorner>-20037508.342789 -20037508.342789</LowerCorner>
        <UpperCorner>20037508.342789 20037508.342789</UpperCorner>
      </ows:BoundingBox> 

If these tags are removed there is no exception when running WmtsTests. According to the OGC-standard (http://portal.opengeospatial.org/files/?artifact_id=35326) a bounding box is optional for a TileMatrixSet item, I think (not 100 % sure what they mean in the documentation). Is it so that WmtsParser does not support a BoundingBox in a TileMatrixSet?

**Comment by pedwik** [comment]
I see now that this is exactly what is handled in the patch you sent, sorry.

**Comment by FObermaier** [comment]
The issue is not that there is a BoundingBox, the issue is that LowerBound and UpperBound are lacking the ows prefix.
```XML
<ows:BoundingBox crs="urn:ogc:def:crs:EPSG:6.3:900913">
  <ows:LowerCorner>-20037508.342789 -20037508.342789</ows:LowerCorner>
  <ows:UpperCorner>20037508.342789 20037508.342789</ows:UpperCorner>
</ows:BoundingBox>
```
would work

**Comment by pauldendulk** [comment]
Looks like @FObermaier fixed this with this commit: https://github.com/BruTile/BruTile/commit/53cf9539751bca40fef0ffb6785fb07941de2bb5
