### ISSUE TITLE
Converting between tile service protocols

### ISSUE THREAD

**Issue by rowanwins** [BruTile/BruTile#34]
Hi there, 

Im trying to understand a bit about how BruTile works. I currently have access to a TMS and I'm wondering if BruTile is a good choice to help me convert it into a WMTS so that it can be consumed in ArcMap, I'm essentially trying to trying to trick ArcMap.

I've seen ArcBruTile however it looks like its running a fair way behind BruTile so I'm wondering if there is anything in the new code base that would make my job easier.

Thanks,
Rowan

**Comment by pauldendulk** [comment]
This is basically what ArcBruTile does. It reads a TMS and shows it in ArcMap. It does its own rendering. Is it not possible to add a custom TMS to ArcBruTile? @bertt?

What are you using to publish the TMS?

**Comment by bertt** [comment]
Correct in ArcBruTile you can add TMS via option 'Add TMS Service' -> 'Add TMS Provider'. Here an example screenshot for the U.S. National Park services:
![tmsprovider](https://cloud.githubusercontent.com/assets/538812/10962722/acf85d8e-839a-11e5-9529-8074791ad8b8.png)

**Comment by rowanwins** [comment]
Gday @pauldendulk & @bertt ,

Thanks for the suggestion however I was actually wanting to create my on ArcMap addin specific to one TMS. I started looking at the code for ArcBruTile however because it seemed a fair way behind BruTile so I thought I'd check in here first to see if there was anything relevant for my task that had been more recently introduced.

I'll close the issue but if you have any other ideas let me know.
Thanks,
Rowan

PS No offence meant to ArcBruTIle project by the way, its a very good project!
