### ISSUE TITLE
Question on breaking changes

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#35]
Hi,
I am trying to replace Brutile.dll and BrutileDesktop.dll in a DotSpatial plugin that currently used Brutile v0.10. There is one breaking change that I have not found documentation on:

The old code set the Height and Width when initializing a TileSchema. How should this be changed, given that Height and Width are no longer properties of TileSchema?

**Comment by FObermaier** [comment]
It is TileWidth and -Hight are part of the Resolution now

**Comment by pedwik** [comment]
When creating the url for a web request the following code was used before:
...
url.AppendFormat("&WIDTH={0}", schema.Width);
url.AppendFormat("&HEIGHT={0}", schema.Height);

Should schema.Width be replaced with schema.GetTileWidth(levelId) then? If so, what is levelId?

Also, the following code was used when instantiating a TileSchema:
var schema = new TileSchema
            {
                Format = "image/png",
                Srs = info.CRS,
                Height = 256,
                Width = 256,
            };
Should the Height and Width be dropped (since there are neither any setters for TileWidth and TileHeight, nor for the Resolutions object)?

**Comment by pedwik** [comment]
What should the key value be in Resolutions then?

**Comment by pauldendulk** [comment]
The Width and Height should be dropped from the TileSchema and should be added to each Resolution (because in WMTS it could theoretically change from level to level). 

Although in your case you could omit the Width and Height from the Resolution because in the latest version of BruTile they default to 256.
