### ISSUE TITLE
Add BruTile/BruTile to Travis CI

### ISSUE THREAD

**Issue by FObermaier** [BruTile/BruTile#36]
@pauldendulk please consider adding BruTile to [Travis CI](https://travis-ci.org/).
I think everything is prepared for a passing build. and we can include a badge in the `ReadMe.md`

**Comment by pauldendulk** [comment]
Thanks, I was not aware of Travis, seems a great idea. BruTile has automated builds in teamcity. It should be fairly easy to move it to Travis.

**Comment by pauldendulk** [comment]
Before I join travis it shows 'Organizations determine whether the application can access their data' and list all the organizations that I am a member of. Most are not relevant for this. Perhaps I should create a specific account for Travis?

**Comment by FObermaier** [comment]
I did join using my github account. That way I could set it all up for SharpMap, GeoAPI, NTS all from one user account. But that is your decision.

**Comment by FObermaier** [comment]
Btw, the CI on TeamCity has been out of sync for quite some time.
http://teamcity.codebetter.com/viewType.html?buildTypeId=bt707

**Comment by pauldendulk** [comment]
oh yes, I had forgotten about that. I'll fix it.

**Comment by pauldendulk** [comment]
Fixed the codebetter build for now. It was still pointing to codeplex. 

I have knowledge of teamcity. So that might be easier for me. Is there a reason to prefer Travis CI? Perhaps better hosting? Where could we expect the newest .net versions and Xamarin support?

**Comment by pauldendulk** [comment]
Travis CI has beta warning: https://docs.travis-ci.com/user/languages/csharp/ Probably not better there. Perhaps just stick with teamcity.

**Comment by pauldendulk** [comment]
Added a shield. Clicking it brings you to teamcity but the build status of the shield is not effected by breaking it. Should I use a different url?

**Comment by FObermaier** [comment]
> Where could we expect the newest .net versions and Xamarin support

As Xamarin drives mono, the support might be better on travis as the build server itself is running on linux. I agree that teamcity has the nicer frontend, but a couple of weeks ago it was dreadfully slow.

ATM it is ok

**Comment by pauldendulk** [comment]
Well Xamarin Studio is released for Windows and Mac not for linux so not sure if it works frictionless.
