### ISSUE TITLE
Does Google map is supported any more?

### ISSUE THREAD

**Issue by am2222** [BruTile/BruTile#39]
Hi,
I have a question..Does this plugin supports google maps any more?I want to use it in dotspatial..I could not see google maps in the examples
```
ar tileSource1 = KnownTileSources.Create(KnownTileSource.OpenStreetMap)
var tileSource2 = KnownTileSources.Create(KnownTileSource.MapQuestAerial)
var tileSource3 = KnownTileSources.Create(KnownTileSource.BingHybrid)
var tileSource4 = KnownTileSources.Create(KnownTileSource.StamenTonerLite)
var tileSource5 = KnownTileSources.Create(KnownTileSource.EsriWorldShadedRelief)
```
Thank you so much

**Comment by pauldendulk** [comment]
It is not supported specifically. Although it is still possible to use 'google map' and 'google terrain' with the generic capabilities. See Samples\BruTile.Demo.

The repo still holds the obsoleted GoogleRequest which was recently updated @ahuarte47, you could also copy that into you local repo.

You could also look at @petlof's project. It is an attempt to reverse engineer the Google v3 api: https://github.com/petlof/brutile-googleV3
