### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#40]
Hi,
I get a compilation errors when building 0.18.1.

I am using Visual Studio 2013, Update 5. Have installed .Net 4.5.2. No problems when opening solution, just had to let VS restore Nuget references.

Compile error: "Unespected character $" on line 26, ArcGisTileSource.cs:
return new BasicRequest($"{baseUrl}/tile/{"{0}/{2}/{1}"}");

Should it be @ instead of $? Have never seen $.

**Comment by pauldendulk** [comment]
This is a C# 6 feature which is not standard supported in VS2013.

I never tried C# 6 in VS2013 (went to VS2015 instead) but I believe it should be possible. Take a look here: http://stackoverflow.com/a/32010632/85325
