### ISSUE TITLE
Load MBTile Files

### ISSUE THREAD

**Issue by manpreetg** [BruTile/BruTile#41]
Can we load MBTile file using this library?

**Comment by pauldendulk** [comment]
You can load tiles from an mbtiles database, yes.

Is that what you mean?

**Comment by pauldendulk** [comment]
Here is a unit test that could show you how to use it: https://github.com/BruTile/BruTile/blob/master/Tests/BruTile.MbTiles.Tests/MbTilesTileSourceTests.cs

**Comment by manpreetg** [comment]
Thanks Paul for a quick response. I will use it, and its looking great.

Thank you 
Regards
Manpreet S. | iOS Developer
W: netsetsoftware.com <http://netsetsoftware.com/>| P: +91 9915379166

**Comment by manpreetg** [comment]
Is there a way to convert the MBTilesTileSource to MapTileSource.. Like this library doing https://github.com/altso/MBTiles

**Comment by pauldendulk** [comment]
BruTile has no dependency on these specific uwp classes. I am now looking at those classes for the first time. Nice to see they adopted the BruTile architecture :)

[MapTileSource](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.maps.maptilesource.aspx) has a member DataSource which can be assigned by a [CustomMapTileDataSource](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.maps.custommaptiledatasource.aspx) and it looks like you need to implement the eventhandler for BitmapRequested which need to get something called ```PixelData```. [Here](https://msdn.microsoft.com/en-us/library/windows/apps/mt219700.aspx) they set the raw pixels. Now a question is how to convert BruTile tile stream, which is an in image (mostly png or jpg), to PixelData. I assume there is an easier way than traversing all the pixels. Perhaps you can load the BruTile image stream into a native bitmap and then get a pointer to its data as PixelData (which is a RandomAccessStreamReference I believe)

**Comment by pauldendulk** [comment]
oh look. This project you pointed to solved all this in just one class file:
https://github.com/altso/MBTiles/blob/master/MBTiles/MBTileSource.cs

**Comment by manpreetg** [comment]
yes. But it only works on Windows Phone. I am trying to run it on Universal Windows App. For Windows 10.

**Comment by pauldendulk** [comment]
What if you just try to compile that individual class?

**Comment by manpreetg** [comment]
Thanks Paul. the issue was with the latest SQLitePCL for windows 10. I resolved.
