### ISSUE TITLE
How to add a WMTS using brutile and sharpmap

### ISSUE THREAD

**Issue by am2222** [BruTile/BruTile#43]
Hi,
I am confused with new version of Brutile and can not figure out how to create an tilelayer using BruTile to use in sharp map.
Here is my loval wmts layer addres
http://212.50.254.204:7080/PBS/rest/services/MyPBSService1/MapServer/WMTS/tile/1.0.0/MyPBSService1/default/GoogleMapsCompatible//{TileMatrix}/{TileRow}/{TileCol}.jpeg
                   
Can some one helps me with it?

**Comment by pauldendulk** [comment]
SharpMap uses an older version of BruTile. This might cause the problem. 

If your tile set is google compatible. You could try this:
```
var myWmtsTileSource = new HttpTileSource(new GlobalSphericalMercator(), "http://212.50.254.204:7080/PBS/rest/services/MyPBSService1/MapServer/WMTS/tile/1.0.0/MyPBSService1/default/GoogleMapsCompatible//{z}/{y}/{x}.jpeg", name: "WMTS Source");
```

**Comment by FObermaier** [comment]
Wrong button, sorry

**Comment by am2222** [comment]
thanks for your answer,I tried and I could figure out how to create myWmtsTileSource  but when I add it  to sharp map layer it causes problem. How can I manage to fix the problem?

**Comment by am2222** [comment]
this is the error that I get:
`An unhandled exception of type 'System.MissingMethodException' occurred in SharpMap.dll

Additional information: Method not found: 'Void BruTile.Cache.MemoryCache`1..ctor(Int32, Int32)'.`

**Comment by pauldendulk** [comment]
I looks like you are referencing different versions of BruTile in different projects.

**Comment by am2222** [comment]
So I should rebuild sharpmap.dll with new BruTile?I faced some problem compiling its source I am trieing now,I hope I can fix it because I really need it

**Comment by pauldendulk** [comment]
I would try to get this working with the SharpMap and the BruTile version it is using right now. If you miss parts of BruTile you could just copy/paste them into your own source code. 

Perhaps the HttpTileSource does not exist in the SharpMap version. In that case copy that class from BruTile to your own project.

Other advise: Try to get the layer working in some of the BruTile or Mapsui samples first.

**Comment by am2222** [comment]
Thanks for your advice..I'll try it now and I'll share the results..

**Comment by am2222** [comment]
I tried to copy nessesary files such as HttpTileSource and GlobalSphericalMercator to my solution but these classes raises errors too, Can you please share me the source that you tested with current sharpmap dlls?
thank you for your helps

**Comment by am2222** [comment]
I tried to fix errors when I copy classes from BruTile to my solution and these erros still remains.How Can I manage to fix them?They are conversation type error :(

`Severity	Code	Description	Project	File	Line
Error	CS1503	Argument 3: cannot convert from 'BruTile.ITileSchema [E:\Majid\3.3.95\\Extention\ITileSchema.cs(10)]' to 'BruTile.ITileSchema [E:\Majid\3.3.95\SharpMap1.1\BruTile.dll]'	Extention	E:\Majid\3.3.95\\Extention\TileSchema.cs	180
Error	CS1503	Argument 1: cannot convert from 'BruTile.ITileSource [E:\Majid\3.3.95\\Extention\ITileSource.cs(9)]' to 'BruTile.ITileSource [E:\Majid\3.3.95\SharpMap1.1\BruTile.dll]'	Extention	E:\Majid\3.3.95\\Extention\backgroundLayer.cs	88
Error	CS1503	Argument 1: cannot convert from 'System.Collections.Generic.IList<BruTile.Resolution> [mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]' to 'System.Collections.Generic.IList<BruTile.Resolution> [mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]'	Extention	E:\Majid\3.3.95\\Extention\TileSchema.cs	109
Error	CS1503	Argument 3: cannot convert from 'BruTile.ITileSchema [E:\Majid\3.3.95\\Extention\ITileSchema.cs(10)]' to 'BruTile.ITileSchema [E:\Majid\3.3.95\SharpMap1.1\BruTile.dll]'	Extention	E:\Majid\3.3.95\\Extention\TileSchema.cs	156
Error	CS1503	Argument 3: cannot convert from 'BruTile.ITileSchema [E:\Majid\3.3.95\\Extention\ITileSchema.cs(10)]' to 'BruTile.ITileSchema [E:\Majid\3.3.95\SharpMap1.1\BruTile.dll]'	Extention	E:\Majid\3.3.95\\Extention\TileSchema.cs	170
Error	CS1503	Argument 3: cannot convert from 'BruTile.ITileSchema [E:\Majid\3.3.95\\Extention\ITileSchema.cs(10)]' to 'BruTile.ITileSchema [E:\Majid\3.3.95\SharpMap1.1\BruTile.dll]'	Extention	E:\Majid\3.3.95\\Extention\TileSchema.cs	179
`

**Comment by pauldendulk** [comment]
I would think that if you cannot convert from BruTile.ITileSchema  to BruTile.ITileSchema, you still have references to two different BruTile versions.

**Comment by am2222** [comment]
In fact I am using the old version of BruTile which is used in sharp map,I just added classes which gave me errors for example I forced to copy ITileSchema  from githubs source into solution and it seems the errors are because of this...Sorry for my noob questions but I dont know how to fix this problem
thank you

**Comment by am2222** [comment]
This topic also Helped me..Sharp map version 1.2 works fine now

**Comment by roya-dalvand** [comment]
Hi 
I try to add WMTS layer To sharpMap 1.2 and BruTile 0.18.1.0 Bellow Code Not Working for me  and No Exception occurred.
`   string wmtsUrl = "http://10.180.129.89:7080/PBS/rest/services/sat/MapServer/WMTS?";
            var myWmtsTileSource = new HttpTileSource(new BruTile.Predefined.GlobalSphericalMercator(), wmtsUrl);

            TileLayer tt = new SharpMap.Layers.TileAsyncLayer(myWmtsTileSource, "WMTSS");
            addBackMap(opens);`
` private void addBackMap(SharpMap.Layers.TileLayer tl)
        {
               
                //tl.TargetSRID = 4326;
                MaBo.Map.BackgroundLayer.Clear();
                MaBo.Map.Layers.Clear();
                MaBo.Map.ZoomToExtents();
                MaBo.Map.BackgroundLayer.Add(tl);
                MaBo.Refresh();
            
        }`

![capture](https://user-images.githubusercontent.com/35399074/34975174-d9300800-faa5-11e7-8cb1-c7f5aa98d1a3.PNG)

**Comment by pauldendulk** [comment]
The xml at the bottom is the capabilities of the WMTS. You can use the url to the capabilities to create the WMTS TileSource. 

```
   var stream = httpClient.GetStreamAsync("http://10.180.129.89:7080/PBS/rest/services/sat/MapServer/WMTS/1.0.0/WMTSCapabilities.xml").Result;
   var myTileSource = WmtsParser.Parse(stream).First();            
```

**Comment by pauldendulk** [comment]
@roya-dalvand Actually you should create a new issue to ask a question like this.

**Comment by pauldendulk** [comment]
great, I answered:
https://github.com/BruTile/BruTile/issues/43#issuecomment-357869058

Actually you should create a new issue for this.

Paul

**Comment by roya-dalvand** [comment]
@pauldendulk 

"An exception of type 'System.IndexOutOfRangeException' occurred in BruTile.dll but was not handled in user code /Index was outside the bounds of the array." Exception happens in the following line:
var myTileSource = WmtsParser.Parse(stream).First();   
![untitled2](https://user-images.githubusercontent.com/35399074/34981648-5e4efd4a-fabd-11e7-8eb1-e42b2cc09cf4.png)

**Comment by roya-dalvand** [comment]
I Create new issue To find the answer:
https://github.com/BruTile/BruTile/issues/81
