### ISSUE TITLE
Add WMS example to Brutile.Demo?

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#46]
Is it possible to add an ordinary WMS map to the map list in the Brutile.Demo application? It would be great as an example. I suspect that the item called "WMS called through tile schema" is actually WMCS?

I have tried by creating a TileSource object, and borrowed the class WcsTileSource from Dotspatial's web map plugin for this, which implements ITileSource. There are no errors triggered but no map is displayed. A problem is that the data source is not freely available, thus preventing testing.

**Comment by pauldendulk** [comment]
The service is an ordinary WMS. It is called through a WMSC schema. What is your need? I is possible to use BruTile to call the WMS in the usual way (full screen images). I have to had something like Mapsui's ImageLayer. This is not something I will pick up soon. 

It should at least be possible to show the WMS like in the sample.

**Comment by pedwik** [comment]
My need is just to try to get it work with a Swedish WMS source for ortophotos. I tried to define the schema by using info from GetCapabilites, which felt promising. But I do not know how to figure out the Resolutions as you do in WkstNederlandSchema example, leaving them out will raise an exception.

**Comment by pedwik** [comment]
It works for me now, after struggling with the schema.
