### ISSUE TITLE
System default proxy

### ISSUE THREAD

**Issue by Lunat1q** [BruTile/BruTile#51]
Hello, is there a way to use system default proxy in requests? I'm getting 407 error all the time

**Comment by pauldendulk** [comment]
I am not using a proxy myself. You could try two options:

- Set WebRequest.DefaultWebProxy. BruTile is using HttpWebRequest so this should be used if I understand it correctly. https://msdn.microsoft.com/en-us/library/system.net.webrequest.defaultwebproxy(v=vs.110).aspx
- HttpTileSource takes a tileFetcher argument which is a method to override the fetch request, so this way you can implement it itself. Take a look at the known tile sources:
https://github.com/BruTile/BruTile/blob/master/BruTile/Predefined/KnownTileSources.cs
And the implementation of HttpTileSource itself:
https://github.com/BruTile/BruTile/blob/master/BruTile/Web/HttpTileSource.cs

Please let me know if that works for you.

Btw, what do you expect as a way to work with proxies? What kind of solution do you prefer having to work with proxies?

**Comment by Lunat1q** [comment]
Sorry for delayed reply.
Example - i work behind corporate proxy (non transparent) which require login and apss. I just couldn't setup BruTile somehow to work through it.
