### ISSUE TITLE
WMS UpdateSequence conversion error when string

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#52]
According to OGC the "updateSequence" capabalities attribute is optional and can be a string, but in WmsCapababilities.cs, line 83, only integers are accepted and an exception is raised if not. If the UpdateSequence property should remain an integer, my suggestion is to change the code from

```
if (att != null)
{
   UpdateSequence = int.Parse(att.Value, NumberFormatInfo.InvariantInfo);
}
```

to 

```
if (att != null)
{
    int val; 
    if (int.TryParse(att.Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out val))
        UpdateSequence = val;
}
```

**Comment by pedwik** [comment]
Included in 55#

**Comment by pauldendulk** [comment]
Good find! I changed the field to a string as it should be according to the spec.
