### ISSUE TITLE
MapQuest needs API key

### ISSUE THREAD

**Issue by Mangepange** [BruTile/BruTile#53]
MapQuest does no longer accept tile requests without specifying an API key. KnownTileSources.Create needs to be updated in order for it to include this key.

**Comment by pauldendulk** [comment]
Thanks for the warning.

As a workaround you could create your own HttpTileSource based on the code that is now in KnownTileSources.cs. The HttpTileSource takes an apiKey argument as is used in some of the other samples. Take a look:

https://github.com/BruTile/BruTile/blob/master/BruTile/Predefined/KnownTileSources.cs

**Comment by pauldendulk** [comment]
I am going to remove MapQuest. I can't easily find information on how to fix this. On the MapQuest main site they use MapBox arial tiles. It was just a sample.

**Comment by pauldendulk** [comment]
Funny to see Esri has the same problem:
![image](https://cloud.githubusercontent.com/assets/963462/20701546/f1e415ee-b613-11e6-838b-fe0d0df99db7.png)
