### ISSUE TITLE
Change Proposal: Switch to SQLite-net PCL package in Brutile.MbTiles 

### ISSUE THREAD

**Issue by plamen-i** [BruTile/BruTile#58]
Hi,

Recently I made some testing of free GIS packages (NTS, OSM, BruTile, Mapsui, etc) and I am very happy how they work (considering beta status of some of them). I'm also happy about multiplatform support, EXCEPT support of SQLite. I'm professional developer (and GIS developer) and previously I used https://github.com/praeclarum/sqlite-net which in my opinion works very well in all platforms and also is recommended by Xamarin (https://developer.xamarin.com/guides/xamarin-forms/working-with/databases/).

BruTile.MbTiles uses another package - https://github.com/oysteinkrog/SQLite.Net-PCL which actually is a fork from previous one. Due to lack of recent support its users migrate to praeclarum's package (https://github.com/oysteinkrog/SQLite.Net-PCL/issues/311). In addition, there's another useful packages which switched same way (https://bitbucket.org/twincoders/sqlite-net-extensions switched same way for v2.0.0-alpha - see https://www.nuget.org/packages/SQLiteNetExtensions/2.0.0-alpha2). Finally, using two SQLite packages in same project also can be problematic.

Can you consider similar switch in BruTile.MbTiles?

Best Regards

**Comment by pauldendulk** [comment]
At the time I made this choice paeclarum's version had little support and no PCL with the profile I needed. 

I did not do a full review but accept your judgement. Also twincoders' switch is telling. So, yes, lets switch. The question is now when to switch. I am currently focused on the Mapsui 1.0 release and have little time for BruTile.

**Comment by plamen-i** [comment]
Actually, in January I downloaded code of BruTile.MbTiles, made required changes and included it in my test solution - everything worked OK. I'm new to GitHub, but I can try to make PR.

**Comment by pauldendulk** [comment]
That would be great. Just create fork, make the changes, send a PR. https://help.github.com/articles/creating-a-pull-request/

**Comment by pauldendulk** [comment]
I published the new version, perhaps you could check it out. https://www.nuget.org/packages/BruTile.MbTiles/
