### ISSUE TITLE
Confused with Origin value

### ISSUE THREAD

**Issue by wangjianpeng** [BruTile/BruTile#60]
I am confused with the origin value set from this code,
~~~
internal GlobalSphericalMercator(IEnumerable<KeyValuePair<string, Resolution>> resolutions, string format = DefaultFormat,
                                         YAxis yAxis = YAxis.OSM, string name = null)
        {
            Name = name ?? "GlobalSphericalMercator";
            Format = format;
            YAxis = yAxis;
            Srs = "EPSG:3857";

            foreach (var resolution in resolutions)
            {
                Resolutions[resolution.Value.Id] = resolution.Value;
            }

            OriginX = -ScaleFactor * TileSize;
            OriginY = -ScaleFactor * TileSize;

            Extent = new Extent(OriginX, OriginY, -OriginX, -OriginY);

            if (yAxis == YAxis.OSM) OriginY = -OriginY; // OSM has an inverted Y-axis
        }
~~~
I google a tilemap diagram has  mark the origin,  but  i still can't understand how to calculate  origin value with this diagram, anyone can tell me  what the origin meas ?
![TileMap diagram](http://i.imgur.com/MZEPgI5.png)

**Comment by pauldendulk** [comment]
The image shows how the tiles are ordered relative to each other but it does not show how these tiles relate to the coordinate system it represents. So in this case it is not possible to know what the origin value should be. 

BruTile implements several tile service protocols:
- [TMS](https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification)
- OSM (Like TMS with inverted y-axis)
- [WMS-C](https://wiki.osgeo.org/wiki/WMS_Tile_Caching#WMS-C_as_WMS_Profile)
- [WMS](http://www.opengeospatial.org/standards/wms) (tiled requests to a regular WMS - like WMS-C)
- [WMTS](http://www.opengeospatial.org/standards/wmts)
- ArcGIS Tile Server

To learn more about these you should read up on those protocols. I added some links above to the specification but there are probably better places to start reading. For me this is now some years ago so I don't know what the best resources are today. Perhaps Bings documentation is nice: https://msdn.microsoft.com/en-us/library/bb259689.aspx
