### ISSUE TITLE
URL assembly in WMS query for URL including "?"

### ISSUE THREAD

**Issue by collord** [BruTile/BruTile#61]
I'm connecting to a Mapserver WMS server where the configuration file is specified as part of the URL like http://server/cgi-bin/mapserv?map=/var/www/mapfile.map. 

When BruTile does a get capabilities query, the URL it's looking for is http://server/cgi-bin/mapserv?map=/var/www/mapfile.map?REQUEST=GetCapabilities[...] which with the double "?" isn't how things work.

I don't know if other clients (ArcGIS, QGIS) are intentionally more forgiving and yield a "&" at the start of parameters when the url contains a "?" or if it is accidental. It might be nice to be more forgiving.

I'm using BruTile in MapWindow 5. 

Thanks, Jerritt

**Comment by pauldendulk** [comment]
There might be a workaround by adding the ```map=/var/www/mapfile.map``` part as a separate parameter. How are you initializing your WMS? Could you show a piece of your code?

To make this easier BruTile could perhaps check if the url contains a ? and add a & instead in that case. I have to look at that.

**Comment by collord** [comment]
This could be managed either downstream e.g. in Mapwindow or BruTile. One formal way might be for BruTile to manage additional "custom parameters" (what ArcGIS calls them) to send along to the server. 

The offending URL construction code in Mapwindow looks to be:


    internal static class BruTileHelper
    {
        private static string GetRequestUrl(string url)
        {
            return string.Format("{0}?REQUEST=GetCapabilities&SERVICE=WMS", url);   //&VERSION=1.1.1
        }

**Comment by pauldendulk** [comment]
The code suggests it is a MapWindows issue  then.

You could try a PR there with something like this:
```
internal static class BruTileHelper
{
    private static string GetRequestUrl(string url)
    {
            var separator = url.Contains("?") ? "&" : "?";
            return $"{url}{separator}REQUEST=GetCapabilities&SERVICE=WMS"; //&VERSION=1.1.1
    }
}
```
