### ISSUE TITLE
what 's the max zoom level is ?

### ISSUE THREAD

**Issue by wangjianpeng** [BruTile/BruTile#62]
i set the new GlobalSphericalMercator(16, 23) ,  and zoom level to 20, i got httprquest 404 error.
for example , the  request http://c.tile.openstreetmap.org/20/858534/456399.png , got error.
is the max zoom level 19 ?

**Comment by FObermaier** [comment]
The valid zoom level range is specific to the  service. According to the [openstreetmap wiki](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers) the range for standard openstreetmap is currently [0, 19]
