### ISSUE TITLE
Why is TileIndex level a string?

### ISSUE THREAD

**Issue by charlenni** [BruTile/BruTile#64]
I assume, TileIndex.Level is the zoom level of the tile. But why is it a string and not a integer as row and col?

**Comment by pauldendulk** [comment]
This is because in WMTS a level can be indicated by a string. 

I could have solved this differently by adding a level 'Name' for this string value and us an integer in BruTile internally. Still not sure what is better.

**Comment by charlenni** [comment]
Sorry for answering a little bit late 😉

If you work often with zoom level, than it is very annoying to always convert `Level` to an integer value. And normally zoom level is used to make calculations. And if you write in the comments in `TileIndex` for `Level` it is a class and you want to get ride of it.

So my suggestion is, that we add a `int ZoomLevel { get; set; }` or `int Zoom { get; set; }` and replace `string Level` with

    string Level
    {
        get
        {
            return ZoomLevel.ToString();
        }
        set
        {
            ZoomLevel = int.Parse(value);
        }
    }

With this, there are only integers in the structure and we don’t need always a conversion from string to integer, when we want to use the level for calculations.
