### ISSUE TITLE
How Can i use Baidu Map Base BruTile

### ISSUE THREAD

**Issue by gorden1991** [BruTile/BruTile#65]

**Comment by pauldendulk** [comment]
You could take a look at how @bertt did this in ArcBruTile. 

- https://github.com/ArcBruTile/ArcBruTile/blob/598a00e1a471db09a0b44bbf009890d39051f1f6/trunk/ArcBruTile/app/lib/BaiduConfig.cs
- https://github.com/ArcBruTile/ArcBruTile/blob/master/trunk/ArcBruTile/app/commands/AddBaiduTerrainLayerCommand.cs

Let me know how this works out.
