### ISSUE TITLE
IsTileIndexValid?

### ISSUE THREAD

**Issue by JoeCooper** [BruTile/BruTile#68]
MbTilesTileSource has an optimization where the tile index is vetted using a table containing a range for each zoom level.

This takes a fair bit of time to load initially, and when I run it, IsTileIndexValid(X) never actually seems to yield 'false'.

What's the story behind this?

**Comment by pauldendulk** [comment]
In some cases the extent described in the metadata covers the whole world while there is only a small area of tiles available. The _tileRange variable used by IsValidIndex is initialized based on the available tiles. So IsValidIndex is meant to prevent queries for non existing tiles.

How much time does the initialization take on your device? Perhaps the optimization should be optional.

**Comment by JoeCooper** [comment]
All clear.
