### ISSUE TITLE
Determine netStandard versions to supply

### ISSUE THREAD

**Issue by FObermaier** [BruTile/BruTile#73]
BruTile
- [ ] netStandard1.0
- [x] netStandard1.1
- [ ] netStandard1.2
- [ ] netStandard1.3
- [ ] netStandard1.4
- [ ] netStandard1.5
- [ ] netStandard1.6
- [ ] netStandard2.0

BruTile.MbTiles
- [ ] netStandard1.0
- [x] netStandard1.1
- [ ] netStandard1.2
- [ ] netStandard1.3
- [ ] netStandard1.4
- [ ] netStandard1.5
- [ ] netStandard1.6
- [ ] netStandard2.0

BruTile.Desktop
- [ ] netStandard1.0
- [ ] netStandard1.1
- [ ] netStandard1.2
- [ ] netStandard1.3
- [ ] netStandard1.4
- [ ] netStandard1.5
- [x] netStandard1.6
- [ ] netStandard2.0
  
BruTile.Desktop.DbCache
- [ ] netStandard1.0
- [ ] netStandard1.1
- [ ] netStandard1.2
- [ ] netStandard1.3
- [ ] netStandard1.4
- [ ] netStandard1.5
- [ ] netStandard1.6
- [x] netStandard2.0

**Comment by pauldendulk** [comment]
Do I understand it correctly that you are considering support for two .NET Standard profiles for BruTile and BruTile.Desktop? If so, what would be the purpose? From the consumers perspective the lowest profile is the best. The lower the better. From the developers perspective the highest is the best, since it allows the most features. So, if you need to support 1.3 anyway there is no advantage (not for the developer and not for the consumer) to support 2.0?

Or is there something I am missing about compatibility between the 1.x and 2.x line?

**Comment by pauldendulk** [comment]
To avoid complications my idea was not to support PCL and .NET Standard at the same time. To create some extended support for PCL I was thinking to release a 1.0 version of BruTile as it is right now. There are no known bugs from my perspective. Soon after that we could release a BruTile 2.0 with .NET Standard. Which starts from essentially the same code base.

Bug fixes or essential enhancements could be added in both branches.

**Comment by FObermaier** [comment]
I removed all PCL in the `Refactor/netStandard` branch, so once we merge there will be no more PCL.
To release 1.0 as PCL is your choice, but why not just leave it as 0.xx and start netStandard with 1.0-pre1?

**Comment by pauldendulk** [comment]
hmm, that is of course also possible. I would prefer a 1.0 though, although the reasons are a bit vague:
- I want to indicate that the PCL version will have bug fix support for a while. I think by releasing a proper 1.0 it will have the status of a proper version, for which you can expect support.
- You can work with proper semver patch (or maybe minor) versioning.
- Mapsui 1.3 will have to work with the PCL version for a while. It would like it to use a 1.0. Mapsui version 2.0 will probably also support .NET Standard. It will use BruTile 2.0.

**Comment by pauldendulk** [comment]
Releasing 1.0 will not be a big thing. Basically releasing the current version. I could do it today. You merge it into your branch, and we are ready to go for 2.0.

**Comment by plamen-i** [comment]
Maybe it's a little bit early to jump to .NET Standard 2.0 for BruTile.MbTiles - I mean there is no currently replacement for .NET Standard 1.4 UWP support on Windows 10 Mobile. I see that latest version of sqlite-net-pcl still supports .NET Standard 1.1 so is there a problem to support .NET Standard 1.3/1.4 also for BruTile.MbTiles?

**Comment by pauldendulk** [comment]
If sqlite supports .NET Standard 1.1 it is compatible with 1.3 isn't it?

**Comment by plamen-i** [comment]
Yes, .NET Standard 1.1 is compatible with all higher versions, including 1.3 and 1.4.

**Comment by FObermaier** [comment]
I updated the supported netStandard versions (8785ad5). 
* `BruTile.MbTiles` is working -like @plamen-i pointed out- with netStandard 1.1. 
* `BruTile.Desktop` is offered for three netStandard versions:
  * 1.3 with basic FileCache functionality
  * 1.6 with serializeable FileCache functionality
  * 2.0 with DbCache.

**Comment by pauldendulk** [comment]
ah great. So this also satisfies @plamen-i 's concerns?

About Desktop. I do think it is important to have all functionality available for all platforms. So if a user installs BruTile.Desktop he/she should be able to expect the same functionality irrespective of the platform used. So, perhaps the DbCache part should be moved out to it's own NuGet package. And the 1.3 and 1.6 versions should be merged into one 1.6 version.

**Comment by pauldendulk** [comment]
Also, I intent to release the PCL version of BruTile 1.0 today. The consequential merge conflicts are for me to fix.

**Comment by FObermaier** [comment]
@pauldendulk , please see 8adf51f.
I have no problems with you doing the final merge.

**Comment by plamen-i** [comment]
Yes - all my concerns regarding .NET Standard support for BruTile and BruTile.MbTiles are satisfied :-) Thank you both @pauldendulk and @FObermaier!

**Comment by pauldendulk** [comment]
alpha1 of the .NET Core version is pushed. https://www.nuget.org/packages/BruTile/2.0.0-alpha1
