### ISSUE TITLE
Question: How to know y-axis direction of tiles for a WMS service?

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#74]
How do you know the y-axis direction of tiles for a certain WMS-service? The TileSchema property YAxis can take the enum value TMS or OSM, but how do you know which one to choose?

**Comment by pauldendulk** [comment]
Do you mean a WMS-service or a WMS-C-service?

A WMS-service has no inherent axis orientation. The client can choose one. Both can be correct if used consistently. 

For WMS-C-service the orientation is TMS. WMS-C is outdated. So please use another protocol if you can choose: https://wiki.osgeo.org/wiki/WMS_Tile_Caching#WMS-C_as_WMS_Profile

**Comment by pedwik** [comment]
OK, thanks.
