### ISSUE TITLE
MbTiles unit tests don't work with .NET Standard

### ISSUE THREAD

**Issue by pauldendulk** [BruTile/BruTile#77]
Unit testing of SQLite functionality has always been complicated by the dependency on native libraries. In the .NET framework solution of v1.0 this worked automatically. For the v2.0 .NET Standard solution this is broken again. 

Perhaps turning the Test libs into .NET Core libraries might fix it.

**Comment by pauldendulk** [comment]
Perhaps @plamen-i understands whats going on?

**Comment by FObermaier** [comment]
Fixed with a87a02bc7b66828e82157abb5d4ba2f9e02e46cd
