### ISSUE TITLE
.NET Standard version - sqlite nuget switched?

### ISSUE THREAD

**Issue by plamen-i** [BruTile/BruTile#78]
If I'm not mistaken - @FObermaier changed nuget used in .NET Standard version from sqlite-net-pcl to sqlite-net-standard. Is this a unintentional mistake or deliberate change?

**Comment by pauldendulk** [comment]
It seems to make sense, no? Is is now a dependency of a .NET Standard project.

btw, I had also created this issue about MbTiles: https://github.com/BruTile/BruTile/issues/77

**Comment by FObermaier** [comment]
It was intentionally, looking for an sqlite for netstandard.
It seems that this was not the correct decision. The old package is based on the original project repository.
My bad.

**Comment by pauldendulk** [comment]
I don't understand the problem. Which project references which package? And what should it be?

**Comment by plamen-i** [comment]
**To clarify:** Original repository (https://github.com/praeclarum/sqlite-net) is for sqlite-net-pcl package, the same I proposed to switch to a year ago. This package (https://www.nuget.org/packages/sqlite-net-pcl/) is widely used, tested and has 590,242 total downloads. Also, SQLite Net Extensions uses this package, which was one of the reasons to switch to it. Despite its identifier, this package supports .NET Standard 1.1. On the other hand, sqlite-net-standard package is based on fork of original repository, has latest version 7 months old and has only 1,773 total downloads.

**Comment by pauldendulk** [comment]
All clear!

**Comment by FObermaier** [comment]
Fixed with a87a02bc7b66828e82157abb5d4ba2f9e02e46cd
