### ISSUE TITLE
IndexOutOfRangeException occurred in WmtsParser Brutile 

### ISSUE THREAD

**Issue by roya-dalvand** [BruTile/BruTile#81]
"An exception of type 'System.IndexOutOfRangeException' occurred in BruTile.dll but was not handled in user code /Index was outside the bounds of the array." Exception happens in the following line:
var myTileSource = WmtsParser.Parse(stream).First();

`
 System.Net.Http.HttpClient httpClient = new System.Net.Http.HttpClient();
            var stream = httpClient.GetStreamAsync("http://10.180.129.89:7080/PBS/rest/services/sat/MapServer/WMTS/1.0.0/WMTSCapabilities.xml").Result;
            var myTileSource = BruTile.Wmts.WmtsParser.Parse(stream).First();  
`

![untitled2](https://user-images.githubusercontent.com/35399074/34982445-a54db4be-fabf-11e7-81a2-ef3f8a77cf09.png)

**Comment by pauldendulk** [comment]
Could you attach the content of the xml as file to this issue?

**Comment by roya-dalvand** [comment]
@pauldendulk 

[WMTSCapabilities.zip](https://github.com/BruTile/BruTile/files/1634578/WMTSCapabilities.zip)

**Comment by pauldendulk** [comment]
Thanks for providing the xml. I added a unit test for it. The parse succeeds and the result is 3 tile sources. 
https://github.com/BruTile/BruTile/blob/1bc68c13e3876ef795dee10690db79e169312dad/Tests/BruTile.Tests/Wmts/WmtsTests.cs#L204

Which version of BruTile are you using? Perhaps it is a compatibility issue.

**Comment by roya-dalvand** [comment]
Thanks Paul parse was done when I updated BruTile. But This code does not showing the map as background layer for sharpmap 1.2 
`TileLayer opens = new SharpMap.Layers.TileAsyncLayer(myTileSource, "sat");`
`opens.SRID = 3857;`
`opens.LayerTitle = "sat";`
`opens.TargetSRID = 3857;`
`MaBo.Map.BackgroundLayer.Clear(); `
`MaBo.Map.Layers.Clear();`
`MaBo.Map.BackgroundLayer.Add(opens );`
`MaBo.Refresh();`

**Comment by pauldendulk** [comment]
Sorry, I can not help you much here. I do not have access to the service myself. Perhaps you need to call 'zoom to extent' or something like that. Perhaps you can see if there is some error logging in SharpMap. If you can not get it to work ask the question in the SharpMap forum.

**Comment by pauldendulk** [comment]
Closing this. I assume there is no BruTile issue underlying this.
