### ISSUE TITLE
UWP doesn't Support .NetStandard 2.0 in Mobile

### ISSUE THREAD

**Issue by radderz** [BruTile/BruTile#84]
Just an FYI, the move to .NetStandard 2.0 for brutile 2.0 will remove the Windows 10 Mobile due to the requirement of the Fall Creators update for .NetStandard 2.0 and Microsoft are unlikely to be adding this support.

**Comment by pauldendulk** [comment]
I don't know much about UWP. Here is what I know. With the Fall Creators update it is now possible to create a new Xamarin project with .NET Standard 2.0 core libraries. This includes UWP. 

What you are saying is that the Fall Creators update you can create UWP apps, but they do not run on Windows 10 Mobile?

**Comment by radderz** [comment]
Correct, Win 10 Mobile is only in maintenance mode for now so is unlikely to receive the update to .net standard 2.0.

It's just a choice for supporting it or not really. Microsoft barely support it so its a legacy platform realistically.

Once Xamarin.Forms supports .net standard 2.0 in their next major revision then it'll make sense to not worry about uwp mobile anyway. 

Besides if you can make this project work with keeping the .net standard as low as possible then you maximise the support of the different versions of .net. You should only go up to the higher versions once the newer functionality api wise gives a new possibility or improvement overall. .net standard 2.0 would be easier to port to though as it has a much larger set of APIs. But it limits you to the fall creators update which isn't ideal even for pcs.

**Comment by FObermaier** [comment]
Only `BruTile.Desktop.DbCache` is dependant on NetStandard 2.0, or am I missing a point?

**Comment by pauldendulk** [comment]
For BruTile 2.0.0-alpha1 these are the .NET Standard versions:
https://github.com/BruTile/BruTile/blob/master/README.md#brutile-20-prerelease-as-net-standard
So, I think it is not such a problem. 

Projects that need to support Win 10 Mobile could just stay on BruTile 1.0 and Mapsui 1.0.

**Comment by plamen-i** [comment]
BruTile and BruTile.MbTiles support .NET Standard 1.1 so they can be used in Windows 10 Mobile UWP (it supports up to .NET Standard 1.4). This was deliberate request from my side exactly for Windows 10 Mobile (and older Windows 10 Desktop) builds to be supported.

**Comment by radderz** [comment]
@pauldendulk - It isn't just mobile, it's also older builds of Windows 10 Desktop, Enterprises generally lag behind so it could be up to 18 months or more before some companies move to the newer version capable of running the newer .net standard. At this stage it is ok for projects that don't require the DbCache as the rest of the packages are on earlier version of .net standard.

**Comment by pauldendulk** [comment]
I am closing this. 

Good to know that Windows Mobile and older builds of Windows 10 Desktop will not support .NET Standard 2.0. I think with the choices for .NET Standard 1.1 for BruTile (Core) and 1.4 for BruTile.MBTiles we have sufficient compatibility. The Desktop assemblies contain very little functionality and will not be used much.
