### ISSUE TITLE
Add support for vector tiles

### ISSUE THREAD

**Issue by charlenni** [BruTile/BruTile#85]
BruTile is a great library for fetching tiles in bitmap format from URL or MBTiles files. So it would be nice to fetch vector tiles with BruTile too.

If I get it correct, than it should be possible to get URL vector tiles by default. But MbTiles lag of this capability. So it would be nice, if you could add PBF to the MbTilesTypes and extend ReadFormat().

**Comment by pauldendulk** [comment]
BruTile itself does not do anything with vector data itself but can in it's current form already be used for fetching vector tiles. Parsing the tiles to vectors should be done in the calling library. There is a sample for this in Mapsui's vector-tile branch.

**Comment by charlenni** [comment]
Yes, that's what I mentioned above. The fetching part is ready, but the MbTiles part not. It is only the two small changes, than BruTile could used with vector data. And no, no interpretation is needed.

**Comment by pauldendulk** [comment]
I merged the pull request.
