### ISSUE TITLE
could not create ssl/tsl secure channel

### ISSUE THREAD

**Issue by am2222** [BruTile/BruTile#86]
Hi,
While I am using brutiles sharpmap extention I faced this error, in fact it appears rendered tiles. I am working on to find the problem. lets say this is my tile address
`https://syntool-tiles2.odl.bzh/data/ingested/3857_Mean_Sea_Level/MSL_Map_MERGED_Global_IB_RWT_NoGIA_Adjust/tiles.zxy/{z}/{x}/{y}.png`

this works from zoom=2 I tried this code 

```
 Map map = new Map();
            map.BackgroundLayer.Clear();
            var myWmtsTileSource = new HttpTileSource(new GlobalSphericalMercator(),
                "https://syntool-tiles2.odl.bzh/data/ingested/3857_Mean_Sea_Level/MSL_Map_MERGED_Global_IB_RWT_NoGIA_Adjust/tiles.zxy/{z}/{x}/{y}.png", name: "WMTS Source");
            BruTile.TileInfo inf = new BruTile.TileInfo();
            inf.Extent = new BruTile.Extent(0 ,0,90, 66.51326044311185);
            TileIndex ti = new TileIndex(2, 1,"2" );
            inf.Index = ti;
            Uri tileurl=  myWmtsTileSource.GetUri(inf);
            SharpMap.Layers.TileAsyncLayer GoogleTerrain = new SharpMap.Layers.TileAsyncLayer(myWmtsTileSource, "GoogleTerrain");
            GoogleTerrain.SRID = 3857;
           // map.SRID = 3857;
            map.BackgroundLayer.Add(GoogleTerrain);
```

in above code `tileurl`  points to an actual tile, It seems there is sth wrong here but I have no idea where is its source

**Comment by pauldendulk** [comment]
If this is a WMTS then there should be a capabilities url. If you have that you can use that to initialize a WmtsTileSource. It will set the resolutions, tile size and bbox correctly for you.

**Comment by am2222** [comment]
@pauldendulk  in fact it is a simlple `xyz` webservice which server tiles based on `xyx` parameters, I can use it simply in open layers. please look at this example

https://codepen.io/am2222/pen/zWpvmX

in this example the url works fine but when it comes to load it using brutile this error happens. I searched and it seems it is because of some sort of `https` issues. I am still working to find some thing to solve this error. The main problem is that the returned tiles are images which this error which I think the way we connect to and download tiles must need some modifications

**Comment by am2222** [comment]
it seems there must be some solutions like this
https://stackoverflow.com/questions/44644329/httpwebrequest-could-not-create-ssl-tls-secure-channel
but could not make it work. It seems I can not even download a tile using c# but I can download it using browser.

**Comment by am2222** [comment]
Well I set this 

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12; `
tiles are now shown without any problems, it seems it is a security issue

**Comment by pauldendulk** [comment]
Thanks for posting the solution here.

**Comment by am2222** [comment]
@pauldendulk  thank you
