### ISSUE TITLE
Problems running test

### ISSUE THREAD

**Issue by charlenni** [BruTile/BruTile#87]
I forked and downloaded the project to my Win 10 PC and opened the project with VS 2017 15.6.1. Than I tried to run the tests. They work all except the SQLite tests. They throw the following error message:

`Message: System.DllNotFoundException : Die DLL "e_sqlite3": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
`

It seems, that there is a DLL missing. I only found a file "SQLitePCLRaw.provider.e_sqlite3.dll" in the folder Debug\net45.

What is my misstake? What should I change?

**Comment by pauldendulk** [comment]
@plamen-i  is the local expert on sqlite, maybe he can help.

**Comment by pauldendulk** [comment]
@charlenni When I do a clean checkout, build and run all unit tests (using resharper) all tests are green. I'm on a 64 bit machine, Windows 10.

**Comment by pauldendulk** [comment]
@charlenni Could you test this again? This should just work. I need to fix it if it doesn't.

**Comment by charlenni** [comment]
I delete the packages "sqlite-net-pcl" in BruTile.MbTiles.Tests and readded it again. Now I have the Dll in the bin directory and the tests work. Don't know, why this dependencies not added when downloading BruTile, but they aren't.
