### ISSUE TITLE
for offline

### ISSUE THREAD

**Issue by johnhs91** [BruTile/BruTile#89]
Hey

After updating BruTile.MbTiles, I can't set platform "MbTilesTileSource.SetPlatform(platform)" doesn't exist anymore, how do I set the platform?

After the update, my app crash, when trying to get my tiles from database, guess it's because it doesn't set platform?

new MbTilesTileSource(new SQLite.SQLiteConnectionString(path, false), new GlobalSphericalMercator(YAxis.OSM)); 
return null after update, if I just remove the place where I set platform.

Br. John Sørensen

**Comment by johnhs91** [comment]
From 0.19.0 to 1.0.2 btw.
And the RequestHelper.FetchImage is gone too, just copied the function from github to my project, to get it to work.

**Comment by pauldendulk** [comment]
About FetchImage. Nowadays you can use HttpClient for that:
```
        private byte[] FetchTile(Uri arg)
        {
            return _httpClient.GetByteArrayAsync(arg).ConfigureAwait(false).GetAwaiter().GetResult();
        }
```

**Comment by pauldendulk** [comment]
You don't need to set the platform anymore. Perhaps the MBTiles sample can help you. Did you update all nuget packages? MTTilesTileSource can return null to indicate that a tile is not available while it should be according to the schema.

**Comment by johnhs91** [comment]
Did update BruTile and BruTile.MbTiles, the only 2 I use.
So I will try something else, and come back if I still got the problem.

Thank you very much.

**Comment by pauldendulk** [comment]
Please reopen if you have additional information.
