### ISSUE TITLE
Using WMTS with custom CRS as a source

### ISSUE THREAD

**Issue by MaticDiba** [BruTile/BruTile#91]
Hi,
I'm trying to use WMTS which uses custom CRS (EPSG::102060): http://gis.arso.gov.si/arcgis/rest/services/DOF25_2014_2015/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

The issue is that map is not correctly scaled. I think the problem is with the CRS this WMTS is using. I'm not sure how it should be set to work. Is there any example for this issue. Is this even possible to achieve with the current implementation of ButTile?

Any advice or example would be more then helpful.

**Comment by pauldendulk** [comment]
BruTile does not attempt to transform the tiles. It just fetches them and returns them as is. 

I understand there is some disparity between the tiles and some other data. Which other data is this? Is this in EPSG::102060?

What client do you use to show the data?

**Comment by MaticDiba** [comment]
I'm trying to show multiple layers in my app: Google maps, OSM, and this custom layer from the WMTS above. So all the other layers use data in EPSG:3857.

 I would like to use that in Mapsui, but was also testing it in Demo project in Brutile solution.

**Comment by pauldendulk** [comment]
There is currently no support in BruTile or Mapsui to transform tiles. It is probably possible if you write a custom 'TransformingTileLayer' for Mapsui. But transforming tiles is processor intensive and the result can be ugly. 

I vaguely remember that Felix Obermaier once implemented some kind of tile transformation. This might be part of SharpMap.

**Comment by MaticDiba** [comment]
Thanks for the tip. I will try to find and check his solution. 

Keep up the good work!
