### ISSUE TITLE
Extent Represend a Area that cross +-180 Longitude

### ISSUE THREAD

**Issue by cbfrank** [BruTile/BruTile#92]
If an extent crosses the +-180 Logitude, the BruTile doesn't process it.

**Comment by pauldendulk** [comment]
This was never taken into consideration but perhaps it should. What is the current behavior? Does it return the part that is within +-180?

What complicates wrap around is that not every axis behaves the same. Depending on the coordinate system it could be the x axis, y axis or none. Not sure if the ogc has something to specify this for an axis. We should know at which value to wrap around for which axis.
