### ISSUE TITLE
Inherited SRS missing, when deserializing a WMS 1.3.0 GetCapabilities-response

### ISSUE THREAD

**Issue by MatthiasSchilder** [BruTile/BruTile#93]
BruTile 0.22.1. I'm using it within DotSpatial, so there are some constraints, but if this is fixed in a more current release, I'm happy to update.

I'm querying a WMS (GetCapabilies url is [1]) which responds with a nested layer structure. The topmost layer defines a list of CRS/SRS, the nested-inner layers do not advertise CRS/SRS. I assume, in accordance with WMS Implementation specification 1.3.0 [2] (section 7.2.4.6.7 page 26), those nested layers should inherit the CRS/SRS which are defined hierarchically above. When accessing the list of supported CRS/SRS through Brutile.Wms.Layer.CRS/SRS, the list is empty for the nested layers. Also, there is no property to access the parent layer to look for parent CRS.

[1] http://sgx.geodatenzentrum.de/wms_topplus_web_open?SERVICE=WMS&request=GetCapabilities&service=wms&version=1.3.0
[2] http://portal.opengeospatial.org/files/?artifact_id=14416

**Comment by pauldendulk** [comment]
Thanks for reporting it. I will look into this.

**Comment by MatthiasSchilder** [comment]
Did you already had a chance to look into this issue?

**Comment by pauldendulk** [comment]
No, it it looks it going to take a while. Priority now is to get Mapsui 2.0 to release candidate.

**Comment by pauldendulk** [comment]
This will be fixed in the upcoming release, 2.0.2.
