### ISSUE TITLE
Storing data to recreate a TileSource

### ISSUE THREAD

**Issue by sanderswart-atmos** [BruTile/BruTile#94]
I'm trying to find a way to create a persistent list of tile sources. This means that when a TileSource is loaded from this list, it can be recreated to be an exact copy of the original which was stored in that list. The way the sources and providers are implemented right now, there is no way to access the request string or url, which I believe is the minimum that is needed to be able to recreate every TileSource.

My suggestion would be to add a property to ITileSource which contains the url used to create the provider. Every implementation of ITileSource could expose additional data which is required to create the provider for that specific TileSource( i.e. the server nodes IEnumerable for an HttpTileSource).

**Comment by pauldendulk** [comment]
Not every ITileSource is a HttpTileSource. An MBTilesSource for example has no url at all. Perhaps it would be possible to expose the url on the HttpTileSource, or expose the Provider which could explose the url in return. However the more is exposed on an interface the less flexible it becomes. I probably won't do that. Perhaps I could come up with some solution with some effort but I don't think I will have time for that soon. 

As you can see the BasicRequests has quite a few private fields that need to be exposed to enable it.
https://github.com/BruTile/BruTile/blob/master/BruTile/Web/BasicRequest.cs
And the provider gets a IRequest should there could be other implementations with other fields.

## Possible workarounds
- Store the variables when they are added. I assume they are added during the runtime of the application. When the user adds them you could store them then.
- Use reflection.
- Use serialization. Not sure if this works. Try ```JsonConvert..SerializeObject(myTileSource)``` and load with ```JsonConvert.DeserializeObject<ITileSource>(json);```. If it works this is probably the best solution.

**Comment by sanderswart-atmos** [comment]
That is true. 

You could add a public SourceString property to the ITileSource interface. This SourceString property could be source independent of the type of source, since every TileSource has to have some kind of link to a location (a path, url, etc) where the data is stored. This string is set in the constructor of the TileSource, where this string is known. 
They only issue here is that you can pass a request directly into the TileSource, which means there is no string known. This is done with the WMTS source and possibly other sources. A workaround would be to take the requestcapabilities request url and add the name and EPSG code to that string. This would give enough information to recreate a WMTS source.

> Store the variables when they are added. I assume they are added during the runtime of the application. When the user adds them you could store them then.

This could work for all sources except the KnownTileSources, for which it should also work in my opinion.

> Use reflection.

This works, but it should be done for every single combination of TileSource/Request which seems like an overkill.

> Use serialization. Not sure if this works. Try JsonConvert..SerializeObject(myTileSource) and load with JsonConvert.DeserializeObject<ITileSource>(json);. If it works this is probably the best solution.

This doesn't work because of the interfaces. It is possible to serialize the object, but it's impossible to deserialize.

**Comment by pauldendulk** [comment]
I am not sure what your purpose is. Do you just want some string to identify the tile source or do you want to store all information to rebuilt the tile source? Do you get all information when you serialize it?
