### ISSUE TITLE
Exception thrown when no Title field present in WMTS Capabilities layer

### ISSUE THREAD

**Issue by matthewfender** [BruTile/BruTile#95]
A missing Title field for a layer in a WMTS GetCapabilities document causes an exception to be thrown which prevents any layers from the document from being loaded.
I'm not sure how prevalent this problem is in the wild, but I have only started experimenting with WMTS recently and have already come across an example here:  https://opencache.statkart.no/gatekeeper/gk/gk.open_wmts?Version=1.0.0&service=wmts&request=getcapabilities

There seems to be a deprecated layer at the very beginning of the document, which retains an abstract but little else.

The fix seems simple enough; check for null when accessing the Value field in the WmtsParser.GetLayers method (in WmtsParser), in the same way that abstract already is:

```c#
        private static IEnumerable<ITileSource> GetLayers(Capabilities capabilties, List<ITileSchema> tileSchemas)
        {
            var tileSources = new List<ITileSource>();

            foreach (var layer in capabilties.Contents.Layers)
            {
                var identifier = layer.Identifier.Value;
                //var title = layer.Title[0].Value;
                string title = layer.Title != null ? layer.Title[0].Value : string.Empty;
                string @abstract = layer.Abstract != null ? layer.Abstract[0].Value : string.Empty;
```

I am not familiar enough with Brutile to know what the knock-on effects of an empty Title might be. There also seem to be quite a few other XML fields that are accessed without protection against null, but again I don't know how commonly these would be seen in the field. It seems to me that, even if a layer might be unusable with some of these fields missing, there might be other layers within the document that are OK - so perhaps catching exceptions on a per-layer basis during the Layers foreach might make sense?

**Comment by pauldendulk** [comment]
Thanks for reporting this. 

I don't foresee any problems with an empty title. Best to set it to an empty string and not to null. I will take a pull request on this.
