### ISSUE TITLE
'Getting Started with BruTile' seems to be outdated

### ISSUE THREAD

**Issue by donid** [BruTile/BruTile#97]
The code in this tutorial does not compile anymore.

**Comment by pauldendulk** [comment]
Thanks for letting me know.

**Comment by pauldendulk** [comment]
I update the 'getting started' wiki:
https://github.com/BruTile/BruTile/wiki/Getting-Started-with-BruTile

To prevent this in the future I also added a [sample project](https://github.com/BruTile/BruTile/blob/master/Samples/BruTile.GettingStarted/Program.cs) with all the code in the 'getting started' wiki. A maintainer needs to realize that if this code needs changes the 'getting started' wiki needs to be updated.
