### ISSUE TITLE
Migrate manual available?

### ISSUE THREAD

**Issue by pmeems** [BruTile/BruTile#98]
With MapWindow5 (https://github.com/MapWindow/MapWindow5) we use BruTile v0.22.1
I see much newer versions are available.
Do you have a migration manual so I can see how much work it will be to upgrade to the latest version or are all versions backward compatible?

**Comment by pauldendulk** [comment]
They are not all backward compatible but it looks like there were not that many changes.

We use [semver](https://semver.org) from 1.0.0. 
- So from 1.0.0 up to 1.0.3 there were no breaking changes. 
- Going to 2.0.0 the only breaking change was going to .NET Standard. 
- From 2.0.0 up to 2.0.2 there are no breaking changes.

From 0.22.1 to 0.22.2 to 1.0.0 there seems to be very few changes looking at the release notes. You can take a look yourself [here](https://github.com/BruTile/BruTile/releases).

**Comment by pmeems** [comment]
Thanks Paul for your answer. I'll try to upgrade to v1.0.3 first.
Our project is not .NET Standard so I'm not sure if it is wise to mix .NET versions.
